### ISSUE TITLE
Alternative boot menu not being displayed for Grunt / Careena

### ISSUE THREAD

**Issue by bobbarnes1981** [MrChromebox/scripts#100]
Hi,

I am using a HP Chromebook 14 (Careena / Grunt).

I used the firmware script to install RW_LEGACY and at first I thought it didn't work as CTRL-L just show a white screen with "Alternative Firmware Menu". However pressing 1 will launch Uboot and 2 will show the coreboot logo and allow access to the menu. Should a boot menu be displayed?

After choosing UEFI USB it does attempt to boot from a linux USB but the graphics are not in the right mode I think as it is sort or corrupted.

**Comment by MrChromebox** [comment]
sounds like things are broken on Google's end unfortunately. You should be presented with a list of boot options when pressing CTRL+L (it works on other AMD Chromebooks). The display is corrupted (colors are off) and that's on the stock firmware as well. You can boot/run Ubuntu 19.04/19.10 without issue but some other distros seem to be having issues. Best you can do right now is file a bug report with Google

**Comment by hackedXD** [comment]
Has this been fixed? I am struggling to open up my chromebook and so cant disable wp so help would be appreciated.

**Comment by MrChromebox** [comment]
I don't know, I don't have one of these to test, and it's not something I can fix on my end. But either way, AMD Stoneyridge Chromebooks run Linux **terribly** so it's a waste of time either way
