### ISSUE TITLE
Falco checksum fail

### ISSUE THREAD

**Issue by bambi666999** [MrChromebox/scripts#101]
I have been trying to flash full rom firmware on my HP Chromebook 14, and am stuck at the below error message.

....................................
Downloading Full ROM firmware
(coreboot_tiano-falco-mrchromebox_20191129.rom)

Firmware download checksum fail; download corrupted, cannot flash.
..................................

I followed the website's instruction and executed the below cmd line :

cd; curl -LO https://mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh

Thanks in advanced for your assistance!

**Comment by bambi666999** [comment]
OK, I found the problem.  The file name is wrong in sources.sh.  It should be coreboot_tiano-falco-mrchromebox_20191201.rom.  So, I downloaded sources.sh manually, edited it, modified firmware-util.sh, and now I have full rom firmware!

Thank you for the great script/package!

**Comment by MrChromebox** [comment]
sorry about that, fixed
