### ISSUE TITLE
Script error? 

### ISSUE THREAD

**Issue by Jake-Ell** [MrChromebox/scripts#103]
I have an HP G1 chromebox, I7-4600U, tried to run the script and this is what I got back...

firmware-utils.sh: line 1: html: No such file or directory
firmware-utils.sh: line 2: syntax error near unexpected token `<'
'irmware-utils.sh: line 2: `<head><title>404 Not Found</title></head>

I'll look at the script and compare it to previous versions but wait a while to hear back before I try anything.

**Comment by MrChromebox** [comment]
there's nothing wrong with the script, your error indicates the file wasn't downloaded correctly
