### ISSUE TITLE
Lenovo ideapad 100s not recognized

### ISSUE THREAD

**Issue by 1nikolas** [MrChromebox/scripts#105]
Hello. I have a Lenovo ideapad 100s (Windows version) and I'm trying to install Chrome OS Firmware to replace Windows with Chrome OS (if its even possible (??) ). I ran the script on bootable Ubuntu but cpu/device name is not recognized correctly. Also when I choose 9 nothing happens. Here is a screenshot 
![fUCE2xW](https://user-images.githubusercontent.com/30593419/71528831-7ba39d80-28ea-11ea-8655-f5d73b7ae65b.png)

Thanks in advance

**Comment by MrChromebox** [comment]
You can't run my script, or use ChromeOS firmware, on a non-ChromeOS device. What you're doing won't work, since the hardware is different. I'd recommend looking at Project Croissant on XDA if you're trying to hack ChromeOS to run on standard PC hardware

**Comment by 1nikolas** [comment]
Thanks for your response. The problem is that I can't boot any chromium on this laptop even though this same model ships with chrome os.. I dont know whats wrong, it just stucks on the boot screen...

**Comment by MrChromebox** [comment]
unfortunately that's not something I can help with, and even though Lenovo sells the same model with ChromeOS, the hardware is not exactly the same.
