### ISSUE TITLE
chromebook pixel 2013,there is no sound output when plug in earphone 

### ISSUE THREAD

**Issue by canserliao** [MrChromebox/scripts#107]
In chromebook pixel 2013,there is no sound output when plug in earphone. Sound is still output from speaker in cloudready image. Even I use ubuntu to check if this is an OS issue. But it is still fail in ubuntu.

**Comment by MrChromebox** [comment]
this isn't an issue with my script, nor my firmware, best I can tell. 

It works under ChromeOS, so has to be something different there vs Cloudready or mainline Linux.

**Comment by canserliao** [comment]
Thanks for the reply!
You meant your firmware can work under chromeOS; so after run the script how to install chromeOS (or which chromeOS can be used to install?)

**Comment by MrChromebox** [comment]
one cannot run ChromeOS with the UEFI firmware. you need to use CloudReady, or a hack solution like Chromefy / project croissant
