### ISSUE TITLE
Pixel 2013 fan issue

### ISSUE THREAD

**Issue by renr4** [MrChromebox/scripts#108]
The fan on my pixel 2013 runs and stops every 3 seconds all the time with zero cpu load. Should it work like that?

There is an error in the original firmware when the fan doesn't work at all, when chromebook turns on on battery, and I remember that it seems to have been fixed, so maybe it’s somehow connected.

**Comment by MrChromebox** [comment]
no, it shouldn't. What distro/kernel is being used?  I'll test here on my Pixel

**Comment by MrChromebox** [comment]
tested with UEFI firmware MrChromebox-4.11.1 on Mint w/kernel 4.15.0-70, fan idles around 3000 rpm and is steady, adjusts under load/temp increase as expected, verified using ectool
