### ISSUE TITLE
Acer Chromebook 14 black screen when selecting boot menu or boot manager

### ISSUE THREAD

**Issue by nonetrix** [MrChromebox/scripts#111]
everything works as expected I get the cutie bunny uwu and etc but when when I press esc it still works but selecting boot menu or manager only gives me a never ending void just like my soul when I'm depressed after beating my meat to fat anime boobs questioning my life decisions.. oh yeah GitHub issue things uhh ｗｅｅｄｅａｔｅｒ

10/10 would recommend

**Comment by MrChromebox** [comment]
replied to your post on reddit. Also, not a script issue (belongs under Firmware)
