### ISSUE TITLE
Full ROM firmware download fails on SONA

### ISSUE THREAD

**Issue by maaso** [MrChromebox/scripts#113]
>*********************************************************
>**   Device: HP Chromebook x360 14 (SONA)
>** CPU Type: Intel KabyLake
>**  Fw Type: Full ROM / UEFI (MrChromebox-4.10 10/28/2019)
>**           Update Available (03/17/2020)
>**    Fw WP: Disabled
>*********************************************************

When trying to update my current full ROM firmware to the latest version, I get the following message:
>Downloading Full ROM firmware
>()
>
>curl: Remote file name has no length!
>curl: try 'curl --help' or 'curl --manual' for more information
>Firmware download checksum fail; download corrupted, cannot flash.

AFAICS, this is because there is no entry for sona in `sources.sh` so the file to download is not found. Is sona no longer supported?

**Comment by MrChromebox** [comment]
SONA uses the NAMI image, I'll take a look at see what's going on shortly
