### ISSUE TITLE
can not recongize usb devices in Boot Manger, pxiel 2015

### ISSUE THREAD

**Issue by wenyyang** [MrChromebox/scripts#115]
I have succefully run this scripts on google chromebook pixel 2015 (Samus). Now I can enter the Boot Manger.
I make a win10-install U-disk using rufus-3.10p.exe, but my U-disk cannot be auto-recongized by machine. In another word, the boot manger did not show any other options except EFI Interal Shell and SATA:KINGSTON RBU-****.
Stucking in this step during install windows 10. Help pls

**Comment by MrChromebox** [comment]
did you try the solutions listed in https://mrchromebox.tech/#faq ?
If the USB isn't being recognized, easiest thing to do is use a different USB
