### ISSUE TITLE
What is the option : Clear NVRAM exacly ?

### ISSUE THREAD

**Issue by slotsec** [MrChromebox/scripts#116]
i cant find info please help :(

![fwutil_wp_disabled](https://user-images.githubusercontent.com/49119376/81506411-18783d80-92c4-11ea-8dc3-00d7192c0ca6.png)

**Comment by MrChromebox** [comment]
the option does not exist when not running my UEFI firmware (and no UEFI firmware is available for Apollolake devices). Since you are running stock firmware, there is no NVRAM to clear.
