### ISSUE TITLE
CN60 hangs if no display connected

### ISSUE THREAD

**Issue by bishopdynamics** [MrChromebox/scripts#119]
Hello,
First let me say that your work has been incredibly valuable to me, I have been able to rescue a lot of e-wasted chromeboxes and turn them into useful PCs; they even make acceptable ESXi hosts! Thank you so much for your hard work!

I have several Asus CN60 (Panther, Haswell) units, which I have flashed with the Full UEFI Firmware. I have noticed that if I do not have a display connected, the unit seems to hang very early in booting, and will not continue to booting an OS. Traditionally in this kind of situation I would use a cheap HDMI edid emulator to fool the hardware into thinking a display is connected, but this does not seem sufficient in this case.

I have observed this across several different releases of the firmware over the years, including the latest (06/04/2020). However, I have never seen anyone else mention it, including in this issue tracker. 

I would be happy to help troubleshoot in any way I can.

Thank you!

**Comment by MrChromebox** [comment]
I've found this tends to be an issue with the bootloader (grub), rather than the firmware, but I've not extensively tested it. But I have users running Chromeboxes as headless audio servers (I forget which distro they run) and there's no issue
