### ISSUE TITLE
something gose wrong when im flashing

### ISSUE THREAD

**Issue by planegor** [MrChromebox/scripts#124]
hello,im flashing firmware-util.sh on my pixelbook 2013

after copying the code on the shell,

it gose to:
uefi-flash.sh: warning: uefi-flash.sh: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

Downloading supporting files...
Error downloading one or more required files; cannot continue

i dont know how to fix this problem,some advises?

**Comment by MrChromebox** [comment]
> it gose to:

clearly you are not following directions on my site or you would not get that **warning** (it's not an error)

> Downloading supporting files...
> Error downloading one or more required files; cannot continue

something caused the download from the server to fail, not anything I can do about that really
