### ISSUE TITLE
issue with booting

### ISSUE THREAD

**Issue by tcavlee** [MrChromebox/scripts#127]
I am having issues with my Asus Chromebox 3 not booting from bios to loaded program. I have to plug in a different keyboard and unplug power multiple times while hitting the esc button F12 button enter button or control alt delete before I can get into the boot menu where I can change the boot order to the hard drive. Once I do this the program loads. I have had this problem with Gallium, Ubuntu, Manjaro, Linux lite, Linux cinnamon and a couple of other distros that i can't remember.
Here is what I get for the system:
Operating System: Manjaro Linux
KDE Plasma Version: 5.19.3
KDE Frameworks Version: 5.72.0
Qt Version: 5.15.0
Kernel Version: 5.6.19-2-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3-7100U CPU @ 2.40GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

I have updated the firmware and I am running UEFI from MrChromebox.

**Comment by MrChromebox** [comment]
this isn't a script issue, please re-submit under firmware
