### ISSUE TITLE
Download firmware-util.sh error

### ISSUE THREAD

**Issue by TM-001** [MrChromebox/scripts#131]
run  `curl -LO mrchromebox.tech/firmware-util.sh` 
download file error 

(checked carefully  command is right)

Some wrong with github download?
Thanks for any advise.

**Comment by MrChromebox** [comment]
things fail to download all of the time, could be DNS, could be github, could be any number of things. Without the error there's no way to say, and even then.

**Comment by cshirey1980** [comment]
Okay well here is my latest and greatest in this issue I was wanting to check out cloud ready so I downloaded it on the USB with their writer after attempting to load it and restart black screen of death has arrived . You can see the screen is lit but there is nothing on it no cursor no prompt no nothing and every key that I hit every anything that I try makes no difference

**Comment by cshirey1980** [comment]
Well like I said the screenshots completely black so there's nothing to really show period it was the 2013 pixel so it might just be the end of the road for it but it was working fine before I tried to do cloud ready I don't know what happened

**Comment by TM-001** [comment]
Yes, the problem is internet. I can't download directly file by github. You know, some locate internet is limited.
Thanks for reply.
