### ISSUE TITLE
It says I need a password when I run cd ~; curl -L -O http://mrchromebox.tech/firmware-util.sh; sudo bash firmware-util.sh

### ISSUE THREAD

**Issue by bruhmoment1234567** [MrChromebox/scripts#134]
When I run cd ~; curl -L -O http://mrchromebox.tech/firmware-util.sh; sudo bash firmware-util.sh, it says I need a password from the local system administrator. Here is an image of the problem.

![Screenshot 2020-10-28 at 2 34 31 PM](https://user-images.githubusercontent.com/73610306/97481137-bfac6800-192a-11eb-9cd8-fe727c3c7100.png)

**Comment by MrChromebox** [comment]
there's only a password if you set one, or enabled debugging features when you shouldn't have. there is no sudo password by default

**Comment by bruhmoment1234567** [comment]
The thing is, I never set a password.

**Comment by bruhmoment1234567** [comment]
And I don't have debugging features enabled.

**Comment by MrChromebox** [comment]
dunno what to tell you, there's not one by default. Exit and re-enter developer mode and don't click/enable anything not explicitly stated to do so

**Comment by bruhmoment1234567** [comment]
Ok.
