### ISSUE TITLE
DNS fails for mrchromebox.tech, www.mrchromebox.tech and wiki.mrchromebox.tech

### ISSUE THREAD

**Issue by daviddean99** [MrChromebox/scripts#135]
Looks like there is a DNS problem with the mrchromebox.tech domains - none resolve and downloads all fail?

Seems the nameservers at quesera.com are down and not serving the domain:

mrchromebox.tech results:
i.ns.quesera.com.Server Timed out...
j.ns.quesera.com.Server Timed out...

Also check here:

https://mxtoolbox.com/SuperTool.aspx?action=dns%3amrchromebox.tech&run=toolpage

This will be affecting everybody, not just my connection.

**Comment by MrChromebox** [comment]
DNS host having issues, it's being worked on
