### ISSUE TITLE
UEFI sound not working.

### ISSUE THREAD

**Issue by ergpopler** [MrChromebox/scripts#138]
I was able to get the UEFI script thing to work, and boot into Kubuntu 20.04, and KDE Neon, both had no sound, via the internal speakers, or via the headphone jack, i tried fiddling with alsa and whatever, didn't work.  Bluetooth worked though, and was able to get sound to work with that, but it had horrible sound quality(i don't exactly know why).

**Comment by MrChromebox** [comment]
this 1) isn't a script issue, and 2) isn't a firmware issue. It's a kernel/driver/Alsa UCM config one.

**Comment by ergpopler** [comment]
Is it solvable?

**Comment by MrChromebox** [comment]
depends on the device/platform, distro, kernel, etc.

GalliumOS has working audio for some older platforms. Newer devices don't work regardless.  Check out https://www.reddit.com/r/GalliumOS and https://www.reddit.com/r/chrultrabook
