### ISSUE TITLE
Upgrade Chromebook soldered RAM possibility？

### ISSUE THREAD

**Issue by waitlamp** [MrChromebox/scripts#141]
I‘m considering upgrade my Chrome book pro (XE510C24) soldered RAM.
For some low-cost windows tablets, their soldered SDRAM and EMMC can be cheaply replaced by a larger version, these devices' hardware are very similar to Chromebook. 
the key to achieve it is the device have a high-grade version, or its BIOS support larger SDRAM (though the device have not). 
Does UEFI full ROM support a larger SDRAM? (my device have not any larger RAM version)
Could you tell me some about the Memory part in the bios?

**Comment by MrChromebox** [comment]
this isn't a script issue, please re-open under Firmware repo - thx
