### ISSUE TITLE
Could unsupported devices be supported in the future?

### ISSUE THREAD

**Issue by techboyg5** [MrChromebox/scripts#144]
Hi there!
My friend just got a Chromebook `BLOOGLET` and it doesn't work on either firmware at the time, according to the [Supported Devices](https://wiki.mrchromebox.tech/Supported_Devices) page.

My question is, could unsupported devices (especially this one) be supported in the future or will they be unsupported forever?

**Comment by MrChromebox** [comment]
duplicate of #89, closing
