### ISSUE TITLE
HP Chromebook won't boot after firmware

### ISSUE THREAD

**Issue by elmejix** [MrChromebox/scripts#146]
I run the ChromeOS Firmware Utility Script on an HP Chromebook 14-ak040nr to use it with Linux Mint but now is not booting.

This is what I did:
Removed the screw for write protection, enabled developer mode, follow all the Chrome procedure to reset the Chrome system, opened a shell window to run the ChromeOS Firmware Utility Script [Install/Update UEFI (Full ROM) Firmware], created a back up of the chrome firmware on a USB drive, everything went well, but when I rebooted the computer (option R), the computer won't boot or show the logo of your script.
I turned it off, plug in a USB drive to install Linux Mint, but the same situation: is not booting.
The screen shows that is powered but stays blank.

I have used the script before on an Acer Chromebook CB5-571-C4G4 and now is working perfectly with Linux Mint, the only thing I did differently this time was not to clear the UEFI NVRAM before rebooting.

I have tried to manually clear the NVRAM by holding Refresh and turning it on, but nothing happens.

I will really appreciate any help regarding restoring the Chrome firmware to try the procedure again or instructions on how to make the computer boot with a USB drive to install Linux.

The attached picture is before removing the write protection screw, wanted to see if that particular Chromebook did not need to remove such screw.

Thank you in advance for any help
![Script screen](https://user-images.githubusercontent.com/78320739/106396756-fa191b80-63d7-11eb-94a6-60139d153dc0.jpg)

**Comment by MrChromebox** [comment]
> the only thing I did differently this time was not to clear the UEFI NVRAM before rebooting.

why would you clear the NVRAM before rebooting? what park of my documentation ever mentions needing to do that?

> I have tried to manually clear the NVRAM by holding Refresh and turning it on, but nothing happens.

that doesn't clear the NVRAM, there's no way to do so.

> The attached picture is before removing the write protection screw, wanted to see if that particular Chromebook did not need to remove such screw.

my site tells you what write protection method is needed for each device

> Thank you in advance for any help

https://wiki.mrchromebox.tech/Unbricking
