### ISSUE TITLE
When creating a backup copy of the stock firmware in firmware-util.sh, the downloading step freezes for ASUS Chromebox CN60

### ISSUE THREAD

**Issue by nich227** [MrChromebox/scripts#147]
I successfully replaced the stock firmware with the Coreboot firmware. The issue that I had before though was that whenever I backed up my stock firmware to a USB stick, then it went into the process of downloading the firmware, it froze. I pressed CTRL+C to exit the script, then ran it again and went through it and picked No when it asked to create a backup copy, and it went through successfully. Maybe there is an issue in the code when the user selects Yes to backup my stock firmware?

**Comment by MrChromebox** [comment]
there's no issue with the script/code when choosing to back up, you just happened to have a hiccup downloading the first time thru. The two events (you choosing to backup, and the download failing) are purely coincidental
