### ISSUE TITLE
Chromebook Pixel 2013 (Link board)  "Firmware download checksum fail...  ... cannot flash"

### ISSUE THREAD

**Issue by mgexyz** [MrChromebox/scripts#150]
I'm using the MrChromebox script to install Cloudready on my immaculate but 'end-of-life' Chromebook Pixel 2013.
It starts downloading the Full ROM firmware but after a few minutes gives a red-text message:
Firmware download checksum fail; download corrupted, cannot flash.
Repeated this a few times but the download fails every time.
Any suggestions?
Thanks very much,
Mike
![File_000 (2)](https://user-images.githubusercontent.com/80688915/111154593-4afd6180-858b-11eb-8eb3-698853b0ddd7.jpeg)

**Comment by MrChromebox** [comment]
the file exists and I have no problem flashing here on my LINK, so likely just a random download failure
