### ISSUE TITLE
ARM64/AARCH64 Support

### ISSUE THREAD

**Issue by krome-3k** [MrChromebox/scripts#159]
Please support devices with the Mediatek MT8183C SoC. There are quite a few of these out there.
Thanks in advance.

**Comment by MrChromebox** [comment]
support for what exactly?

**Comment by krome-3k** [comment]
> support for what exactly?

I want to run your firmware utility script but i am on ARM64 chromebook. Please help.

**Comment by MrChromebox** [comment]
but to do what? Legacy Boot mode doesn't exist on ARM devices, so there's no RW_LEGACY firmware. ARM devices typically don't use UEFI either. And you can boot Linux with the stock firmware. So I'm not sure what you want exactly

**Comment by krome-3k** [comment]
> but to do what? Legacy Boot mode doesn't exist on ARM devices, so there's no RW_LEGACY firmware. ARM devices typically don't use UEFI either. And you can boot Linux with the stock firmware. So I'm not sure what you want exactly

I want to remove chrome os and install another distro.. maybe dual boot?

**Comment by krome-3k** [comment]
> > but to do what? Legacy Boot mode doesn't exist on ARM devices, so there's no RW_LEGACY firmware. ARM devices typically don't use UEFI either. And you can boot Linux with the stock firmware. So I'm not sure what you want exactly
> 
> I want to remove chrome os and install another distro.. maybe dual boot? Please tell me how to.

**Comment by MrChromebox** [comment]
that's not something you need my script for. How-to is very device specific, and not something I'm able to help with. Look at Arch ARM to see if your device is supported/how-to, or other distros for ARM Chromebooks

**Comment by krome-3k** [comment]
Arch linux as per https://archlinuxarm.org/platforms/armv8/mediatek/acer-chromebook-r13 boots into a blank screen but is for MT8173. As per https://archlinuxarm.org/platforms/armv8/generic doesn't boot with a beep. Archbox https://github.com/lemniskett/archbox and archrome https://github.com/gsf/archrome run into errors. Ubuntu server ARM64 and Debian ARM64 isos don't boot with a beep. Please help.

**Comment by MrChromebox** [comment]
I'm not sure what you think I can do - your device simply isn't supported by those distros. No custom firmware is going to magically change that.

**Comment by krome-3k** [comment]
Is it possible to port any of them for my device? Maybe by building from source? I am noob coder but i can follow instructions and google bugs. Can you tell me how is hardware support added say to archlinux if i build from source? Or do i have it all wrong and it cant be done? Please guide me.

**Comment by MrChromebox** [comment]
I'm not an expert on ARM ChromeOS devices or ARM for Linux, there's nothing I can do for you I'm afraid. I'd recommend you ask for help on the Arch forums/IRC etc.

**Comment by krome-3k** [comment]
Okay, thanks anyway.

**Comment by MrChromebox** [comment]
there is no such thing as legacy boot on an ARM platform, legacy BIOS does not exist.
While the hooks for AltFw might exist, there's no universal payload for ARM the way there is on x86.
I have my hands full with 300+ x86 devices, I'll let someone else handle ARM if they want

**Comment by scorpio79-debug** [comment]
![Image](https://github.com/user-attachments/assets/dd6166a5-e716-48c6-a429-62e69a91de46).   Look at this please you mentioned that arm64 don't have legacy boot but this does

**Comment by scorpio79-debug** [comment]
I added one this is what I was just trying to tell you in the first place chrome OS developer website shows how to do it
