### ISSUE TITLE
No boot on KASUMI

### ISSUE THREAD

**Issue by GT3CH1** [MrChromebox/scripts#160]
After flashing the full UEFI firmware for KASUMI (Acer 311, The AMD variant) the device never boots. I can see the backlight turning on for less than a second, and then immediately turning off. I have tried using the firmware-util script, and a ch341a programmer, with no luck getting the firmware to boot.

I am able to restore the stock firmware via the programmer.

**Comment by MrChromebox** [comment]
If you have a Suzy-Q, can provide a debug build to try and troubleshoot, but short of that nothing I can do other than check that the config is consistent with the other StoneyRidge boards. I have a BARLA and LIARA here and they both work with the current 4.14 release firmware

**Comment by GT3CH1** [comment]
I just found a "quirk"
After reflashing the stock firmware, and enabling legacy booting again,
I've ended up in the UEFI  firmware. So I guess it works but not as
intended?

**Comment by MrChromebox** [comment]
that's not a quirk, Stoneyridge devices, like all other devices using the new alternative bootloader menu, use Tianocore for legacy boot instead of SeaBIOS
