### ISSUE TITLE
MrChromebox script not working Asus CN60

### ISSUE THREAD

**Issue by chris1892006** [MrChromebox/scripts#164]
The command isn't working.

curl -L -O https://mrchromebox.tech/setup-kodi.sh && sudo bash setup-kodi.sh

![IMG_20210930_155747](https://user-images.githubusercontent.com/91700437/135529124-57f52444-6a29-4fae-b752-02f555e4f7a8.jpg)

**Comment by MrChromebox** [comment]
script and documentation updated with info on how to mitigate this

**Comment by chris1892006** [comment]
May you pretty please link me to this documentation you speak of to mitigate this?  I'm a noob to this Chromebox stuff.
