### ISSUE TITLE
check for existed resource and skip downloading

### ISSUE THREAD

**Issue by terrancewong** [MrChromebox/scripts#167]
Not downloading everything again is much appreciated.

**Comment by MrChromebox** [comment]
we're talking <1mb of additional data downloaded. I could checksum everything and verify before re-downloading but that just seems like an extra hassle given the small benefit.

**Comment by terrancewong** [comment]
just slightly more friendly to slow connections and multiple offline flash :-P

**Comment by MrChromebox** [comment]
if you've modified my script for offline use, then adding a check for the required utilities and not downloading them should be trivial ;-)
