### ISSUE TITLE
Berknip (AMD Ryzen3) Linux boot - black screen

### ISSUE THREAD

**Issue by sngx13** [MrChromebox/scripts#169]
Hi,
Any idea whether AMD chromebooks support booting Linux? Every latest distro boots and only displays mouse cursor :|
Thank you.

**Comment by MrChromebox** [comment]
because the AMDGPU drivers are hosed. You can try booting with kernel param 'nomdeset' and see if that helps

**Comment by sngx13** [comment]
Would love to see if anyone has feedback or a work around for this. I've rolled back to secure mode for now :(

**Comment by MrChromebox** [comment]
zork (Zen+) based Chromebooks need to boot Linux with the `iommu=pt` parameter currently
