### ISSUE TITLE
Firmware utility script requires password

### ISSUE THREAD

**Issue by VDH-tech** [MrChromebox/scripts#174]
I tried to run download and run a firmware utility script for chrome os it requires a password to proceed. I don't know what to do. Please help! 
![IMG_20220108_130915_597](https://user-images.githubusercontent.com/97244677/148644084-5231d298-6b07-423b-aec3-5d490a937d1a.jpg)

**Comment by MrChromebox** [comment]
there is no default sudo password, unless you do something you're not supposed to do (like enable debugging options). Exit and re-enter developer mode without doing anything you shouldn't, and there won't be a password
