### ISSUE TITLE
Disabling software write-protect and clearing the WP range   chromebook c630 

### ISSUE THREAD

**Issue by xxmNIe** [MrChromebox/scripts#175]
i'm using the MrChromebox script to install bios
![Screenshot 2022-01-14 21 35 34](https://user-images.githubusercontent.com/15315817/149524463-305d0495-cc7c-4b52-b112-811f83691241.png)
int the  end step ,there is an error:
```
Disabling software write-protect and clearing the WP range

Error clearing software write-protect range; unable to flash firmware.
```
![Screenshot 2022-01-14 21 37 44](https://user-images.githubusercontent.com/15315817/149524726-567e4bef-d4a5-4840-85f3-80ebf9ff7306.png)

i have do something:
```
flashrom --wp-disable

echo "wp false" > /dev/ttyUSB0
echo "wp false atboot" > /dev/ttyUSB0
echo "ccd reset factory" > /dev/ttyUSB0
gsctool -a -I
crossystem wpsw_cur
```
but it is not work

**Comment by MrChromebox** [comment]
> i'm using the MrChromebox script to install bios

no, you're not. You're using someone else's fork of my work, as evidenced by the fact that your device isn't recognized, and that it says it's downloading "from wkkun's mirror" - whoever that is.

Run only the commands listed on my site, and if you have issues then come back and re-open the issue. **You do not need to run any flashrom commands manually!!!**
