### ISSUE TITLE
Intel mei can't work

### ISSUE THREAD

**Issue by wzn556** [MrChromebox/scripts#178]
Thanks for your work for ChromeBook. 
There’re any operating system which can find Intel me, Intel me interface can‘t work under any OS,  it makes the IGPU  can‘t be driven under macos. Windows can't detect TPM, which may also be this reason. Is this my device problem? And is it possible to fix this problem? Thank you.
My Device：Lenvo Chromebook FLEX 5 （AKEMI）
MrChromeBox Version：4.14

**Comment by MrChromebox** [comment]
> There’re any operating system which can find Intel me, Intel me interface can‘t work under any OS, it makes the IGPU can‘t be driven under macos. 

the ME is disabled by coreboot by default. I'm not really interested in enabling it just for MaOS

> Windows can't detect TPM

known issue, being worked on. Nothing to do with the ME

also, closing as this isn't an issue with my scripts, and there are already existing issues for these items in the correct location (MrChromebox/firmware)
