### ISSUE TITLE
Asus Chromebox 3: can't boot from USB-C Power Delivery after flashing UEFI firmware

### ISSUE THREAD

**Issue by bam80** [MrChromebox/scripts#186]
First of all it still boots from power adapter.
Then, if I swap to PD with WP screw in place, LED blinking red and it doesn't boot.
If I remove the screw, it bootloops.

With original firmware, I can boot from PD with screw in place only. If I remove the screw, get bootloop (need to detach from power before removing the screw, otherwise it can still boot).

So it seems no way of using native Linux with PD currently, which is a whole point I bought the device.

Any help? @MrChromebox could you try to reproduce, please?

**Comment by bam80** [comment]
> With original firmware, I can boot from PD with screw in place only. If I remove the screw, get bootloop (need to detach from power before removing the screw, otherwise it can still boot).

This particular issue is reported here:
https://issuetracker.google.com/issues/222675683

**Comment by MrChromebox** [comment]
closing as this isn't a script issue

**Comment by bam80** [comment]
Could we move the issue between the projects maybe?
This should be placed in https://github.com/MrChromebox/firmware/issues probably.

First needs to be reopened:
https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by bam80** [comment]
> Could we move the issue between projects?

@MrChromebox
