### ISSUE TITLE
Linux Mint 

### ISSUE THREAD

**Issue by shadowsmith** [MrChromebox/scripts#189]
Hi.  Running an old Toshiba Chromebook from 2014 era.  Intel.  Swanky.  Ran the firmware script and was able to boot from USB after option 1 and reboot.  Installed Mint.  After reboot, the Toshiba says the OS is not Chrome.  Can’t boot from USB anymore (two beeps).  Reload Google recovery and try again with different version of Linux?  Really wanted to use Mint.  Thanks.

**Comment by MrChromebox** [comment]
* perform ChromeOS recovery
* remove WP screw
* flash UEFI firmware (option 2)
* install Mint from USB

The RW_LEGACY firmware (option 1) is meant for dual booting ChromeOS, if you're going to wipe ChromeOS it becomes problematic.
