### ISSUE TITLE
volteer support?

### ISSUE THREAD

**Issue by lanrat** [MrChromebox/scripts#193]
Is the "volteer" board supported?

I don't see its firmware option listed here: https://github.com/MrChromebox/scripts/blob/master/sources.sh

But it does look like you [explicitly called it out as supported on reddit](https://www.reddit.com/r/coreboot/comments/st5125/comment/hx1umv9/?utm_source=reddit&utm_medium=web2x&context=3).

Thanks.

**Comment by MrChromebox** [comment]
volteer is the baseboard for all TGL Chromebooks, for which I only have RW_LEGACY support currently. Nothing preventing me from releasing UEFI firmware other than time and testers.

**Comment by lanrat** [comment]
I'm happy to help test if needed.

For RW_LEGACY, where can I find information on using this? I'm somehow failing to find the correct results when searching.

**Comment by MrChromebox** [comment]
not sure what you mean by "results"

**Comment by lanrat** [comment]
How I can flash the RW_LEGACY formware to boot linux.

**Comment by MrChromebox** [comment]
using my script. If your device isn't recognized properly, let me know the board name / HWID and I'll add/fix it

**Comment by gitguest0** [comment]
I would be interested in testing as well, i have a lillipup/volteer (Flex 5 13ITL6) device.
I should be able to unbrick the device with a modified SOIC8 clip if that would be necessary.

![s-l1600](https://user-images.githubusercontent.com/109971615/180804991-ef6270e4-3699-4bd7-8ff5-b68fa7e9518d.jpg)
