### ISSUE TITLE
Nothing happens on boot

### ISSUE THREAD

**Issue by dtavilez** [MrChromebox/scripts#194]
Obtained an HP Chromebox. Wanted to spin up Kodi on it. Booted into Developer Mode. Ran MrChromebox script and did a standalone installation instead of dual boot. Ran through the prompts. Said it needed to reboot. Typed "R" for reboot. No on boot, I get black screen out of HDMI port and display port both. Not sure what is going on.

**Comment by MrChromebox** [comment]
this isn't an issue with the script, it's either:

- bad flash / brick (see https://wiki.mrchromebox.tech/Unbricking)
- issue with the display init / cabling etc

I'd test on another display and/or with another HDMI cable
