### ISSUE TITLE
FAQ: Switching back to ChromeOS from UEFI

### ISSUE THREAD

**Issue by RodBarnes** [MrChromebox/scripts#197]
The [FAQ](https://mrchromebox.tech/#faq) has an item addressing how to get back to ChromeOS should one decide the UEFI isn't what is wanted.  The steps include this statement:
> Select the option to restore the stock firmware, follow the prompts and reboot when complete

Looking at `firmware.sh` it appears that the restore option only appears when running `firmware_util.sh` under Linux -- is that correct?  I have not seen this option when running the script under ChromeOS.

**Comment by MrChromebox** [comment]
the option is only shown when running non-stock firmware; all of the options are dynamic based on firmware type
