### ISSUE TITLE
Problems with AMD CPUs?

### ISSUE THREAD

**Issue by fractalf** [MrChromebox/scripts#199]
Hi,
I've read a couple of other issues here mentioning some earlier problems with AMD CPUs.

I just bough a **Lenovo 300e Chromebook 2nd Gen AST (AMD A4-9120C RADEON R4)** with the sole purpose of running Linux on it.

I've tried installing galliumos and ubuntu with *chrx* and Updating the RW_LEGACY firmware with the **firmware-util-sh** script, but nothing seems to be able to boot into anything except ChromeOS, which ofc is completely useless.

So, did I just waste 200$?

Thank you

**EDIT**

When running the firmware-util.sh script I get this sytem info: 

```
Device: Lenovo 300e Chromebook 2nd Gen AMD (TREEYA360)
Platform: AMD StoneyRidge
Fw Type: Stock ChromeOS w/RW_LEGACY
Fw Ver: Google_Grunt.11031.123.0 (01/20/2020)
Fw WP: Enabled
```

**Comment by MrChromebox** [comment]
it's 50-50 if RW_LEGACY works on StoneyRidge devices. GalliumOS doesn't support Stoney at all. UEFI Full ROM firmware will boot, but expect GPU and audio to be problematic, among other things. Stoney just isn't a good platform for running Linux.

**Comment by fractalf** [comment]
Ok, thanks a lot for explaining :) 

..I'm sending this laptop back to the shop for å refund
