### ISSUE TITLE
Intel ME on Lenovo thinkpad 13?

### ISSUE THREAD

**Issue by that0nepers0n** [MrChromebox/scripts#203]
Could there be intel me enabled in the firmware for this machine because I’m pretty sure that’s why I get a gpu error whenever I hackintosh anything above Mojave on my chrome book and I’ve googled for a solution but there’s only a few about chrome books and they all have the same problem with Catalina and others above Mojave

**Comment by MrChromebox** [comment]
on most ChromeOS devices, the ME is hidden from the OS at boot. I'd have to do a custom build to enable it, so something that's best done by the user. Cloning the coreboot repo and compiling yourself isn't all that hard

**Comment by that0nepers0n** [comment]
Ah ok I have no experience with compiling coreboot would you point me in the right direction and how would I go about enabling it? And also that you for all that you do in the community!

**Comment by MrChromebox** [comment]
what is the ChromeOS board name? there are multiple Thinkpad 13's

**Comment by that0nepers0n** [comment]
Sorry was busy it’s “Skylake”

**Comment by MrChromebox** [comment]
not a script issue, closing
