### ISSUE TITLE
"Error trying read config from the 'mrchromebox.tech/firmware-util.sh' file"

### ISSUE THREAD

**Issue by Scottua25** [MrChromebox/scripts#207]
New to me Samsung Chromebox XE300M22
Arrived wiped.
Filpped developer mode switch and let it do it's thing until reaching login screen.
Logged in as chronos
Issued command: cd; curl -LOK mrchromebox.tech/firmware-util.sh
Received the following:

Warning: error trying read config from the 'mrchromebox.tech/firmware-util.sh'
Warning: file
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

After that I'm returned to the command prompt.
Where do I go from here? I'm trying to get home assistant OS on here as the end goal.

EDIT: I will also add that I have good internet signal as pinging google and other random sites works just fine.

**Comment by MrChromebox** [comment]
you copied/pasted the command? sounds like you typed a zero instead of capital O

**Comment by Scottua25** [comment]
Retyped. I don't know how to copy/paste while inside the shell. I typed it several times making sure each time it was correct.

**Comment by MrChromebox** [comment]
where are you copying it from? the k is lower case, and only needed if you get an SSL error otherwise.

https://mrchromebox.tech/#fwscript

**Comment by Scottua25** [comment]
Just updated my last comment as i wasn't sure when you'd see it. sorry.

**Comment by MrChromebox** [comment]
well, it either had an issue downloading the file, or writing it to disk

**Comment by Scottua25** [comment]
What are the steps that need to occur in order for the script to function correctly? I know it needs to be downloaded and from what little I know and can figure out from the commands, it also needs to be copied into the usr/local/bin location and set to 755 permissions. Does it need to be run from that location as well? I can probably figure out how to get it to do what it needs to do now that it’s at least been downloaded.

**Comment by MrChromebox** [comment]
under ChromeOS, normally the script is downloaded and run from the user home dir. copying to /usr/local/bin is not necessary (nor recommended) unless you get an error (not warning) about not being able to exec a script from user home dir (happens on some dev channel builds). Additional utils needed are downloaded to partition 12 of the root device (in this case, /dev/sda12) because that's the only place they can be executed from

**Comment by Scottua25** [comment]
So i guess there's nothing to be done then?

**Comment by Scottua25** [comment]
ok. I finally got there. has to let it boot all the way into chrome and "browse as guest". Once there it let me open your site and then copy/paste worked.

**Comment by MrChromebox** [comment]
> ok. I finally got there. has to let it boot all the way into chrome and "browse as guest". Once there it let me open your site and then copy/paste worked.

that's normally not necessary, but these ancient ChromeOS builds/firmware from 2012/13 certainly have their idiosyncrasies. It's been ages since I tested STUMPY with stock ChromeOS
