### ISSUE TITLE
Error: Image size (2097152 B) doesn't match the expected size (1835008 B)!

### ISSUE THREAD

**Issue by macpit** [MrChromebox/scripts#208]
Hi,

I try to install seabios on Chromebase CA24V2,
and i get this error message:
---
```
Using region: "RW_LEGACY":"seabios-kbl-mrchromebox_20200223.bin".
Error: Image size (2097152 B) doesn't match the expected size (1835008 B)!
FAILED
Restoring PCI config space for 00:1f:5 reg 0xdc
restore_power_management: Re-enabling power management.
```
---
can you please help me to solve the problem, do you need more debug information?

Best regards,

Marc

**Comment by MrChromebox** [comment]
what is the board name in the script menu?

**Comment by MrChromebox** [comment]
RWL payload changed, try flashing again

**Comment by macpit** [comment]
Works, now thank you!
