### ISSUE TITLE
Get unsupported error while running on an Intel based Chromebook

### ISSUE THREAD

**Issue by aknight2015** [MrChromebox/scripts#209]
Here's the whole story.
aknight2015@penguin:~ $ sudo install -Dt /usr/local/bin -m 755 firmware-util.sh
aknight2015@penguin:~ $ sudo firmware-util.sh
grep: /etc/lsb-release: No such file or directory

Downloading supporting files...
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: No such file or directory
Unable to determine Chromebox/book model; cannot continue.

It's likely you are using an unsupported ARM-based ChromeOS device,
only Intel-based devices are supported at this time.

aknight2015@penguin:~$ cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   185    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1441  100  1441    0     0   5458      0 --:--:-- --:--:-- --:--:--  5458
grep: /etc/lsb-release: No such file or directory

Downloading supporting files...
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: No such file or directory
Unable to determine Chromebox/book model; cannot continue.

It's likely you are using an unsupported ARM-based ChromeOS device,
only Intel-based devices are supported at this time.

I'm running it on an Intel Asus Chromebook (C423N)

UPDATE: I entered Crosh and went to it's shell, tried again. Worked like a charm. Can't do it via the Debian Linux terminal. Has to be Crosh.

**Comment by MrChromebox** [comment]
> UPDATE: I entered Crosh and went to it's shell, tried again. Worked like a charm. Can't do it via the Debian Linux terminal. Has to be Crosh.

right, exactly what the documentation says: https://mrchromebox.tech/#fwscript
