### ISSUE TITLE
"Owner has disabled developer mode"

### ISSUE THREAD

**Issue by slandden** [MrChromebox/scripts#211]
WHen I try to enter Developer mode I get "Owner of this device has disabled developer mode", on this eBay-bought laptop (that was sold because it is EOLed by Google), because apparently only Google is the real owner of every device people their hard-earned money for.

It appears this laptop I bought had been Google-locked.

Thanks Our All-Benificient Overlord Google!

On Lenovo x131e.

Didn't see any mention of this issue in the FAQ.

**Comment by slandden** [comment]
Once I connected to the internet it de-enrolled.

But I will leave this issue here because the web-site should say something about this.

**Comment by MrChromebox** [comment]
what exactly would you like me to say about it? Managed devices may or may not allow access to developer mode. Previously managed devices may or may not be properly de-enrolled before resale. That's not really within the scope of what I do though

**Comment by slandden** [comment]
It is just reoate to ypur dev mpde faq

"Google can disable dev mode remotely, and does so xxxxxxxx"
-- 
 Enviado con Tutanota, disfruta del correo seguro y sin publicidad. 



11 jul 2022, 18:44 por ***@***.***:

**Comment by MrChromebox** [comment]
Google doesn't disable it remotely.
