### ISSUE TITLE
Problem flashing ASUS Chromebook Flip CR1100FKA

### ISSUE THREAD

**Issue by hugendudel** [MrChromebox/scripts#213]
Hi folks,

I am trying to install Linux on an ASUS Chromebook Flip CR1100FKA. After successfully running the script, I have the alternative boot loader Tiancore available, but unfortunately not the legacy loader SeaBIOS. I am not sure if it is normal to have the UEFI BOOT loader installed when the BIOS boot loader should be installed? Can you give me some hints on how to debug this further?

Thanks in advance
Harm

**Comment by MrChromebox** [comment]
there is no problem, newer boards/platforms no longer support booting SeaBIOS, so they use Tianocore as the AtlFw bootloader
