### ISSUE TITLE
Two buttons not working on x131e

### ISSUE THREAD

**Issue by slandden** [MrChromebox/scripts#215]
Both my "fn" button, and the "keyboard" (compose?) key on the right side do not work. If I use `evtest` and press them there is an event, but no keys are pressed or released. Using `evtest` also shows that this keyboard is *not* usb, but PS/2: "AT Translated Set 2 keyboard".

**Comment by slandden** [comment]
Because the keyboard is PS/2 I suspect it has to do with the build of coreboot, and that perhaps the keyboard needs SMM.

**Comment by MrChromebox** [comment]
coreboot has nothing to do with the ps2 keyboard, that's handled entirely by the (closed source on this older model) EC

**Comment by slandden** [comment]
Actually atkbd is geting the keycodes (65 and 66), but doesn't know what to do with them, and it is more than just seting key codes in user space, as both of these buttons do fancy things.

**Comment by MrChromebox** [comment]
closing as not a script issue

**Comment by slandden** [comment]
These devices are working great. Thank you so much fr letting me buy these two working computers for $35 each as google leaves people bricks

8 sept 2022, 19:42 por ***@***.***:
