### ISSUE TITLE
hp chromebox g2

### ISSUE THREAD

**Issue by yang149** [MrChromebox/scripts#226]
I would like to ask which is the full ROM firmware of HP Chromebox G2. I can't find it.. Because I need the programmer to write

**Comment by MrChromebox** [comment]
from my scripts:

> KENCH*)                 _x='KBL|HP Chromebox G2' ; device="fizz";;
> export coreboot_uefi_fizz="coreboot_tiano-fizz-mrchromebox_20220718.rom"
