### ISSUE TITLE
CTRL + L doesn't open legacy boot mode 

### ISSUE THREAD

**Issue by newmonksh** [MrChromebox/scripts#228]
Installed the script
![f2](https://user-images.githubusercontent.com/95392220/194723788-7d0beffd-4cef-49ff-91ad-ee3dcef74ad2.png)
![f1](https://user-images.githubusercontent.com/95392220/194723794-b686b77b-823f-4185-a6bc-521320e5c38c.png)

But on reboot pressing CTRL + L shows tow options

![d2](https://user-images.githubusercontent.com/95392220/194723940-e37ca44d-f2b8-4221-8e56-b3ec29d6dbb1.JPG)

but no other option  Legacy Boot Mode or SeaBIOS

Any suggestions

**Comment by MrChromebox** [comment]
that is the expected result on newer Chromebooks. What's the problem?

**Comment by newmonksh** [comment]
Thanks for the quick response , should Reboot, press CTRL+L to boot in Legacy Boot Mode, then press ESC and select your USB from the boot menu... The usb don't get detected on rebooting or after choosing 2TianoCore it boots to chrome os.

**Comment by MrChromebox** [comment]
If Tianocore doesn't boot, then the stock firmware is buggy and little I can do. There is no legacy boot mode in newer Chromebooks, it's related by the alternative bootloader menu. SeaBIOS does not work as an alt payload on these devices.

**Comment by newmonksh** [comment]
Aha... thank you!!!

**Comment by newmonksh** [comment]
to add I was able to disable the hardware WP ,update the firmware via option 2 and make it work.

**Comment by MrChromebox** [comment]
> to add I was able to disable the hardware WP ,update the firmware via option 2 and make it work.

depends on what you mean by "make it work." You'll gain UEFI booting, but lose the ability to run ChromeOS. You won't be able to run Windows, and Linux will have several functional deficiencies (like built-in audio)
