### ISSUE TITLE
Firmware script reports WP enabled even after I took the screw out of Glimmer board

### ISSUE THREAD

**Issue by apsillers** [MrChromebox/scripts#232]
I bought a lot of 1st-gen Lenovo 11e Chromebooks, which uses a GLIMMER board. Over a month ago, I successfully used the script to install full UEFI and convert one of the machines to a ChromeOS-free Linux box.

Today, I tried to convert another 11e, but the Firmware script tells me "Fw WP: Enabled" even after I removed the WP screw. I don't think I've done anything differently with this second machine (but it's possible; it's been a month). However, I noticed the release date on the script output (2022-10-19) was between my last attempt and this one, so that seems like the likelier change.

The device is in developer mode and has the WP screw removed. I am running the script from a `Ctrl+Alt+T` + `shell` terminal. Is there some other step to disabling firmware WP I've forgotten, or has the script's WP detection changed for my board in the last month or two?

My script output is:

```
  ChromeOS Device Firmware Utility Script [2022-10-19] 
 (c) Mr Chromebox <mrchromebox@gmail.com> 
*********************************************************
**   Device: Lenovo ThinkPad 11e/Yoga Chromebook (GLIMMER)
** Platform: Intel BayTrail
**  Fw Type: Stock ChromeOS
**   Fw Ver: Google_Glimmer.5216.198.188 (05/27/2018)
**    Fw WP: Enabled
*********************************************************
**      1) Install/Update RW_LEGACY Firmware 
** [WP] 2) Install/Update UEFI (Full ROM) Firmware 
** [WP] 3) Set Boot Options (GBB flags) 
** [WP] 4) Set Hardware ID (HWID) 
** [WP] 5) Remove ChromeOS Bitmaps 
** [WP] 6) Restore ChromeOS Bitmaps 
*********************************************************
```

Trying option #2 anyway tells me, `Hardware write-protect enabled, cannot flash Full ROM firmware.`

**Comment by MrChromebox** [comment]
nothing has changed with the script's WP detection in probably two years. Your device simply is still grounding the !WP pin, preventing the software WP from being disabled. There may be some metal still around the screw hole which is creating connectivity between the segments.

**Comment by apsillers** [comment]
Okay, that's clear enough! I did have a tough time getting this one out, so that wouldn't surprise me. Worst case I can always run an RW_LEGACY boot on this one system. Thanks!

**Comment by MrChromebox** [comment]
using RW_LEGACY on an EOL system is far from ideal; worst case you could just flash the chip directly using a USB programmer and a chip clip

**Comment by apsillers** [comment]
Problem solved, thanks for the tip! I opened the case back up and blew air into the screw port like my NES cartridge wasn't working; it is now fully writeable. 😁
