### ISSUE TITLE
where is legacy firmware stored?

### ISSUE THREAD

**Issue by narutocanada** [MrChromebox/scripts#238]
hi

I have upgraded the legacy firmware using the script. Everything works. But where is the firmware stored?
Reason I am asking is because I am thinking about using the whole internal (ChromeOS) MMC drive for linux, and completely repartition and reformat and wiping ChromeOS. As long as the legacy firmware is not stored on the internal MMC drive, I do not really care. It might be stored in some EEPROM or something that I do not want to touch. Because I saw something suspicios on the internal MMC drive (32G): (partition 11 and 12)(RWFW)

Model: MMC HBG4a2 (sd/mmc)
Disk /dev/mmcblk1: 31268536320B
Sector size (logical/physical): 512B/512B
Partition Table: gpt
Disk Flags: 

Number  Start        End           Size          File system  Name        Flags
11      32768B       8421375B      8388608B                   RWFW
 6      8421376B     8421887B      512B                       KERN-C      chromeos_kernel
 7      8421888B     8422399B      512B                       ROOT-C
 9      8422400B     8422911B      512B                       reserved
10      8422912B     8423423B      512B                       reserved
 2      10485760B    27262975B     16777216B                  KERN-A      chromeos_kernel
 4      27262976B    44040191B     16777216B                  KERN-B      chromeos_kernel
 8      44040192B    60817407B     16777216B     ext4         OEM         msftdata
12      127926272B   161480703B    33554432B     fat16        EFI-SYSTEM  boot, legacy_boot, esp
 5      161480704B   2308964351B   2147483648B                ROOT-B
 3      2308964352B  4456447999B   2147483648B                ROOT-A
 1      4456448000B  31268511743B  26812063744B  ext2         STATE       msftdata

(parted) quit                                                             

lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
mmcblk1boot0 179:8    0     4M  1 disk 
mmcblk1boot1 179:16   0     4M  1 disk 
mmcblk1      179:0    0  29.1G  0 disk 
├─mmcblk1p3  179:3    0     2G  0 part 
├─mmcblk1p1  179:1    0    25G  0 part /
├─mmcblk1p11 259:3    0     8M  0 part 
├─mmcblk1p8  259:0    0    16M  0 part 
├─mmcblk1p6  179:6    0   512B  0 part 
├─mmcblk1p4  179:4    0    16M  0 part 
├─mmcblk1p2  179:2    0    16M  0 part 
├─mmcblk1p12 259:4    0    32M  0 part 
├─mmcblk1p9  259:1    0   512B  0 part 
├─mmcblk1p10 259:2    0   512B  0 part 
├─mmcblk1p7  179:7    0   512B  0 part 
└─mmcblk1p5  179:5    0     2G  0 part 
sda            8:0    1 125.7M  0 disk 
└─sda1         8:1    1 123.7M  0 part

**Comment by MrChromebox** [comment]
> But where is the firmware stored?

in an SPI flash chip
