### ISSUE TITLE
Error disabling software write protect range when trying to install UEFI

### ISSUE THREAD

**Issue by lordgasmic** [MrChromebox/scripts#239]
This is a similar error to [this issue](https://github.com/MrChromebox/scripts/issues/175), but I am using the scripts found on mrchromebox.tech.

![Screenshot_2022-11-10_02-58-03](https://user-images.githubusercontent.com/831633/200990619-f5d71b1f-9a0e-43eb-87c9-816f103ff391.png)
![Screenshot_2022-11-10_02-58-16](https://user-images.githubusercontent.com/831633/200990642-0be5ddda-dabb-45bb-b315-7f67335ee119.png)

I have tried running the script in both a live-cd and full install of GalliumOS.  I have also tried setting the GBB flags and removing the bitmaps, but ran into similar errors.

**Comment by MrChromebox** [comment]
please exit the script and provide the output of the following two commands from the terminal:

`sudo flashrom --wp-status`
`sudo flashrom --wp-range`

**Comment by Yamboy1** [comment]
I'm also getting the same error. I have flashed about 20-30 of the same type of chromebook and have only seen this error on 2 of them so far.
![Screenshot 2022-11-10 18 55 48](https://user-images.githubusercontent.com/37413895/201013245-cb639683-e755-428b-931b-5211400394f5.png)

![Screenshot 2022-11-10 18 58 34](https://user-images.githubusercontent.com/37413895/201013238-4672382e-0677-4d37-ace5-b7f25a8fad3e.png)

After doing a bit more digging, it looks like the firmware write protect screw had not been removed, but the script had reported that it had been disabled, as you can see from my screenshot.

**Comment by lordgasmic** [comment]
I no longer have access to a `chronos` login since I blew away the partitions when I did a full ISO install of GalliumOS.  I was able to find able to find flashrom in /tmp and here are the results:
![Screenshot_2022-11-10_09-11-44](https://user-images.githubusercontent.com/831633/201114787-bae424af-34a7-4886-897a-9becfedb8339.png)
![Screenshot_2022-11-10_09-11-59](https://user-images.githubusercontent.com/831633/201114829-7fa731d8-cb3a-4663-ac27-88364492ca6d.png)

**Comment by MrChromebox** [comment]
ok, so the problem is software WP is enabled but my script isn't disabling/able to disable it. I'll see if any recent changes may have caused this

**Comment by MrChromebox** [comment]
@lordgasmic this is what I expected. Your hardware WP is still enabled, preventing the script from disabling software WP.

**Comment by lordgasmic** [comment]
Thank you

**Comment by lordgasmic** [comment]
For prosperity's sake, I was able to remove the firmware screw and install the UEFI firmware with no issues.  I couldn't quickly find an image or instructions on how to remove the screw for my laptop so I added it here hoping to help others.

Acer Chromebook 15 CB3-532 hardware firmware screw:
![PXL_20221110_163833129](https://user-images.githubusercontent.com/831633/201178672-bf2545fc-a730-4f70-a263-5ebfbd7a1415.jpg)

**Comment by MrChromebox** [comment]
thanks, I was about to upload it to my site and realized I already had one for Banon, just didn't link it on the devices page. It's there now though :)
