### ISSUE TITLE
asus chromebox 3 - cannot recover chrome from usb

### ISSUE THREAD

**Issue by RichardWright** [MrChromebox/scripts#240]
Hi!

I got a chromebox 3, which has had the UEFI boot enabled and it doesn't have any bootable os installed (It goes to the shell).
I created a chrome recovery usb drive which when selected in the UEFI menu gives me these options:

local image
local image 2
verified image
verified image 2

Currently when I get this menu up, it almost immediately goes to a black screen without any input from me. 

Is recovering chrome os from the usb even possible if UEFI has been enabled and chrome os removed from the drive?

**Comment by MrChromebox** [comment]
You're trying to use ChromeOS recovery media on a device which does not have ChromeOS firmware (and thus no ChromeOS recovery mode). As per https://mrchromebox.tech/#faq, you need to restore the stock ChromeOS firmware before you can use ChromeOS Recovery media
