### ISSUE TITLE
RW_LEGACY --> Kubuntu/unstable/sid: no hibernation, no sleep, no audio

### ISSUE THREAD

**Issue by lizbethmutterhunt** [MrChromebox/scripts#241]
3: having a bluetooth workaround. 
2. and 1. has this to do with the WP disable ? Flashrom meant read-only, and the firmware.sh script doesn't start because of missing html:

sudo firmware.sh
/usr/local/bin/firmware.sh: 1: /usr/local/bin/firmware.sh: cannot open html: No such file
/usr/local/bin/firmware.sh: 2: /usr/local/bin/firmware.sh: Syntax error: redirection unexpected

liz

**Comment by MrChromebox** [comment]
none of these are issues with my script itself
