### ISSUE TITLE
Segmentation fault: Acer Chromebook 712 (C871) (Kindred)

### ISSUE THREAD

**Issue by tkna91** [MrChromebox/scripts#243]
I am unable to update with the following error.

```
./functions.sh: line 334:  3305 Segmentation fault  (core dumped) ${flashromcmd} -r /tmp/bios.bin > /dev/null 2>&1
```
![image](https://user-images.githubusercontent.com/102382754/206742804-7b2c3d6c-f001-472c-8308-e5839bef7908.png)

Environment :
- Acer Chromebook 712 (C871) (Kindred)
- FW: MrChromebox-4.14 07/25/2021
- Battery removed.
- USB Install Image: Ubuntu Server 22.10

Please let me know if you need more information I will get it.

**Comment by MrChromebox** [comment]
flashrom crashed, hard to say way. try live booting a non-server ISO? And no need for battery disconnect

**Comment by tkna91** [comment]
Thanks, but it still doesn't seem to work.

- Ubuntu 22.10 Desktop (64-bit)
- Battery connected

![image](https://user-images.githubusercontent.com/102382754/206846803-5fa74b79-3c2e-4711-ab69-88af1aedca3f.png)

**Comment by tkna91** [comment]
I did the following and succeeded!
- Ubuntu 20.04.5 Desktop (64-bit)
![image](https://user-images.githubusercontent.com/102382754/206852123-4c053237-e4bc-4462-b25d-c491b49cc641.png)
![image](https://user-images.githubusercontent.com/102382754/206852130-680c2090-7b10-4578-8695-d668f3d822db.png)

However, the Arch Linux that was originally installed disappeared from the boot target.
I think this can be fixed by repairing it.
![image](https://user-images.githubusercontent.com/102382754/206852133-b90bef11-e1ba-4f8f-8a4c-914b25520f27.png)

**Comment by tkna91** [comment]
eMMC Device seems to have disappeared

![image](https://user-images.githubusercontent.com/102382754/206852276-fe1230e9-cc57-4463-9c36-bd6ecbfdc213.png)

**Comment by tkna91** [comment]
Sorry. The following resolved the issue.
You can close it if you like.

https://mrchromebox.tech/static/faq.html

> Q: I'm using your UEFI firmware, installed my OS [Linux], and it still boots to the EFI shell - what do I do?
> A: Sounds like your Linux distro doesn't install the EFI bootloader in the default location - no worries, it's an easy fix:
> 
> Type 'exit' to return to the UEFI settings menu, then select Boot Maintenance Manager. From there, select Boot From File, then navigate to and boot from /EFI/[distro name]/grubx64.efi (where [distro name] will be ubuntu, arch, debian, etc). 

![image](https://user-images.githubusercontent.com/102382754/206853215-42641083-8c04-43c7-817e-de3b3d51308c.png)

Thanks for your cool project!
