### ISSUE TITLE
Unable to read current firmware

### ISSUE THREAD

**Issue by KaziRosib** [MrChromebox/scripts#253]
I have been trying to revert to chromeos on my ASUS C523NA Chromebook. But it always says "Unable to read current firmware", no matter which linux operating system i use. It's always the same result. It always shows :-----

''Getting device/system info...
Unable to read current firmware; cannot continue.

Either add 'iomem=relaxed' to your kernel parameters,
or trying running from a Live USB with a more permissive kernel (eg, Ubuntu).

See https://www.flashrom.org/FAQ for more info.''

Now I'm not getting it that, **HOW TO DO ? & WHAT TO DO ?**

**Comment by MrChromebox** [comment]
I'm not able to understand what you are seeing based on your description, so how about you take a pic and post it here?

**Comment by KaziRosib** [comment]
Sorry to bother you sir. But the previous issue is fixed somehow. But now facing new problem with creating the recovery media for my model's leptop. But other seems fine. I know its nothing of your concern, but if you help me, then i will be so thankful to you. Whenever I try to create the media this error massage pops up after varification

![Screenshot 2023-02-04 163904](https://user-images.githubusercontent.com/124389635/216762794-77bb3596-0f12-4962-aff9-4cf394c943c5.png)

**Comment by MrChromebox** [comment]
I would just try it on another machine? maybe you're out of space and the file got truncated? hard to say

**Comment by KaziRosib** [comment]
Tried in 3 different machine 🙂. With different USB sticks. But the result is the same 😅.

**Comment by MrChromebox** [comment]
I have no idea, but this has nothing to do with my firmware or scripts, so closing it.
