### ISSUE TITLE
Firmware update on Cave (c302) leads to Grub boot failure

### ISSUE THREAD

**Issue by mervinbeng** [MrChromebox/scripts#257]
I updated the firmware via the latest firmware script yesterday for my Asus c302 (Cave). After the update and reboot, I see the following on boot:

Welcome to Grub!

error: symbol 'grub_debug_malloc' not found
Entering rescue mode...
grub rescue> 

I'm not familiar with grub rescue.

FYI, the system installed is arch. I am able to boot a usb disk.

**Comment by MrChromebox** [comment]
this almost certainly has nothing to do with the firmware update, more likely you had an Arch/grub update that happened and just now noticed the issue. Either way, boot your rescue USB and reinstall the bootloader (I didn't even think Arch used grub by default).
