### ISSUE TITLE
Error accessing ICH RCRB when running the script on Chromebook Pixel 2013

### ISSUE THREAD

**Issue by tomial** [MrChromebox/scripts#258]
Hi MrChromebox, thanks for the amazing work, I updated the firmware some time ago and after using it for a while, the boot logo inexplicably disappeared and I couldn't access the settings menu with esc, then I found that the system installation failed when it was trying to set up the boot, so I tried to repair the firmware with the script running on a live usb and this error was reported.

Does this mean some kind of hardware issue or simply the firmware broke? can this be fixed?
Thanks!
```
Downloading supporting files...

Getting device/system info...

Unable to read current firmware; cannot continue:

flashrom dc8caac9-dirty on Linux 6.1.11-1-MANJARO (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
coreboot table found at 0xacf67000.
Found chipset "Intel HM75".
Enabling flash write... Error accessing ICH RCRB, 0x4000 bytes at 0x00000000fed1c000
/dev/mem mmap failed: Operation not permitted
FAILED!
FATAL ERROR!
Error: Programmer initialization failed.
```

**Comment by MrChromebox** [comment]
your kernel is not allowing flashrom to read the (memory mapped) flash chip. You can try booting with 'iomem=relaxed' added to your kernel boot params, or try live booting another more permissive kernel (Ubuntu 2204 works fine)
