### ISSUE TITLE
having issue in script

### ISSUE THREAD

**Issue by samgaur25** [MrChromebox/scripts#262]
firmware-util.sh: warning: firmware-util.sh: warning: script from noexec mount; see https://chromium.googlesource.com/chromiumos/docs/+/master/security/noexec_shell_scripts.md

Downloading supporting files...
Error downloading one or more required files; cannot continue

**Comment by Sk44rt** [comment]
cd /home/chronos/user

**Comment by MrChromebox** [comment]
what device? what ChromeOS version? try again after a reboot?

**Comment by Sk44rt** [comment]
> what device? what ChromeOS version? try again after a reboot?

why you? uhhh
simplest fix is go to directory which doesn't have noexec mount

**Comment by MrChromebox** [comment]
closing due to non-reply
