### ISSUE TITLE
script error nu/libc.so.6: version GLIBC_2.33' not found (required by /tmp/flashrom) 

### ISSUE THREAD

**Issue by charles100800** [MrChromebox/scripts#264]
l found an asus 200m running gallium os and its error is ,, unable to read current firmware,cannot continue .

Unable to read current firmware; cannot continue:

/tmp/flashrom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/flashrom)
/tmp/flashrom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/flashrom)

please help me sir

**Comment by MrChromebox** [comment]
GalliumOS is dead, hasn't been updated in almost 4 years. Live boot a 2022 release distro (Ubuntu, Pop, Mint) and update from there
