### ISSUE TITLE
Is this a legacy bios or uefi bios?

### ISSUE THREAD

**Issue by cornflakes6374** [MrChromebox/scripts#265]
i installed the rw legacy bios on my samsung chromebook 4 (octopus/bluebird/casta) and when i entered legacy mode by pressing ctrl-1 then 1 in the dev screen,it showed a coreboot logo, is this a coreboot uefi bios or no??? (Firmware Write Protect is **ENABLED**)
![20230419_143127](https://user-images.githubusercontent.com/116115140/233189162-ed3bae14-751a-4a4a-b398-4bb92eb0203c.jpg)

**Comment by MrChromebox** [comment]
>  is this a coreboot uefi bios or no?

there's no such thing. coreboot is neither UEFI nor BIOS. UEFI and BIOS are two completely separate types of system firmware.

your device, like all newer Chromebooks which use the Alternative Bootloader Menu, uses Tianocore/edk2 (UEFI boot) as the legacy/alternative payload. older Chromebooks used SeaBIOS for legacy BIOS booting
