### ISSUE TITLE
Unable to read current firmware, cannot continue

### ISSUE THREAD

**Issue by Bllckk** [MrChromebox/scripts#266]
Hello, sorry to open this case again but I am actually bad at this type of commands etc. What I did was that my laptop "Acer Chromebook CB314" I installed windows through script but when I want to go to Chrome OS again, at downloading the script again, it shows an error called "unable to read current firmware, cannot continue either add "iomem=relaxed" etc. etc." I am sending photo below, can please someone help? Im struggling so hard today and try to fix it. I am using Ubuntu 20.04.6-dekstop-amd64.iso being configured by Rufus software as the tutorial says: https://medium.com/techtalkers/how-to-restore-a-chromebooks-original-bios-df0b18dfd178 
![IMG_3369](https://user-images.githubusercontent.com/131388410/233429804-ce406c14-6d44-4909-a942-a4b4ed14ca29.jpg)

**Comment by MrChromebox** [comment]
try using ubuntu 22.04/22.10

**Comment by Bllckk** [comment]
> try using ubuntu 22.04/22.10

Hello, I am so grateful for your fast response. I tried installing ubuntu 22.10 and got succesfully in. Thanks a lot, but I dont have my backup firmware, so I tried to install from the recovery image and got error, any fix please.

Download and extract firmware from a recovery image? [y/N] y
Sit tight, this will take some time as recovery images are 2GB+

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4074  100  4074    0     0  36265      0 --:--:-- --:--:-- --:--:-- 36375
`uudecode` was not found. On Debian-based systems, it can be installed
by running `apt install sharutils`.
Downloading/extracting from the recovery image failed

**Comment by MrChromebox** [comment]
the recovery image option doesn't work on a Live USB due to lack of free space required

**Comment by Bllckk** [comment]
> the recovery image option doesn't work on a Live USB due to lack of free space required

So is there any way I can somewhere find and install the recovery firmware? On my Chromebook CB314
