### ISSUE TITLE
at step 2 of the script, error:

### ISSUE THREAD

**Issue by solar2350** [MrChromebox/scripts#267]
Hello,
on a chromebox N62; at step 2, error:

libreelec download complete; installing....
tar: this does not look a tar archive
tar: existing with failure status due to previous errors
error: failed to extract libreelec download: check you internet connection and try again

I don't know what to do, 

thanks in advance

Thierry
PS: I would like to install chromeos and libreelec in dual boot

**Comment by MrChromebox** [comment]
the CN62 is no longer supported for ChromeOS, so I would recommend instead you remove the WP screw, flash the UEFI firmware, then install LE via USB/SD
