### ISSUE TITLE
TOUCHSCREENS AND TOUCHPADS DO NOT WORK ON DELL 7410

### ISSUE THREAD

**Issue by geochensx** [MrChromebox/scripts#271]
I'm trying to install drivers for Coolstar, but the touchpad and touchscreen don't work on the Dell 7410.
I've seen other people say that in version 01/23/2023, the touchscreen works.
I don't really know why this is happening @MrChromebox 

OS: win 11 /Fydeos
Version currently on: 01/29/2023

**Comment by MrChromebox** [comment]
this is not an issue with the script. It's also fixed in the current release.
