### ISSUE TITLE
Stuck on "Press Y to continue or any other key to abort."

### ISSUE THREAD

**Issue by CorpulentBrony** [MrChromebox/scripts#273]
While trying to install the UEFI firmware on CANDY.  I type a capital Y and the letter just appears on screen.  Any letter pressed just appears on the screen and nothing happens.  Hitting enter returns to the main menu and apparently aborts.

**Comment by MrChromebox** [comment]
as I replied on reddit:

typing Y (or y) and pressing enter is the only correct course of action to proceed. If you type anything else and backspace it, it won't work. Y then enter, that's it.
