### ISSUE TITLE
Error when trying to boot from external storage

### ISSUE THREAD

**Issue by MistyWhisp** [MrChromebox/scripts#274]
I dont have anything to take a picture but it says something about gfx graphics failing, any help? I used option 1, i mounted 18.04 ubuntu on a sd card (I've tried other OS too, they all don't work. ) I do not have WP disabled but it is not required for option 1. It did work on other OS, but those couldn't even get past the install screen because something about live images. Any help?

**Comment by MrChromebox** [comment]
this is not a script problem, for general troubleshooting please use the chrultrabook subreddit and Discord server.

Ubuntu 18.04 is now 5 years old, I'd recommend using something newer.
