### ISSUE TITLE
how do i boot iso from the internal storage in a rwlegacy boot?

### ISSUE THREAD

**Issue by cornflakes6374** [MrChromebox/scripts#276]
i want to install gentoo on rwlegacy boot on samsung chromebook 4, but i do not want to etch the iso to the sd card because i dont want to remove chromeos on the hard drive during the install, i want to boot my iso from the internal chromeos storage so i can install the os in a sdcard (the whole os on the sd card, **NOT** the iso.). Is it possible as my sdcard is curently the only storage device i have right now?

**Comment by MrChromebox** [comment]
this isn't a script issue, but no. What you want to do requires 2 USB/SD devices: one to boot the ISO, one to install the OS onto. You can't boot an ISO image from the internal drive filesystem
