### ISSUE TITLE
Dell 3120 (Baytrail/Candy) not waking from sleep windows 10

### ISSUE THREAD

**Issue by maarten682** [MrChromebox/scripts#284]
Running UEFI firmware on a little fleet of these models, pretty much everything works except for one thing; Sleep in windows 10/11 always fails to wake completely (hibernation disabled). 

Going to sleep works fine, wake signals work (including from external events) however im stuck at a backlit black screen and i never get back into windows, the machine is dead at that point. Suspend/wake works great under linux just not windows... is there a driver or setting im missing (everything from coolstar installed) or is this a deeper issue?

**Comment by MrChromebox** [comment]
closing, not a script issue
