### ISSUE TITLE
Downloading 

### ISSUE THREAD

**Issue by ghost** [MrChromebox/scripts#288]
When i choose the second option, the download never start, I live in Cuba... Any recommendations on alternative?

**Comment by MrChromebox** [comment]
for what device / board name? post a pic of the main menu please

**Comment by 7hemel7** [comment]
https://github.com/MrChromebox/scripts/blob/master/sources.sh

**Comment by 7hemel7** [comment]
> https://github.com/MrChromebox/scripts/blob/master/sources.sh


for example    

cd ~/Downloads/
sudo flashrom -w yourname.rom
reboot

**Comment by MrChromebox** [comment]
closing due to lack of follow up
