### ISSUE TITLE
"Running them as root will break things". Does anyone have an updated walkthrough for using the script in 2023?

### ISSUE THREAD

**Issue by createrUA** [MrChromebox/scripts#289]
The updated instructions for the script say: "Running them as root will break things". Therefore, I enter the ctrl+alt+T as a normal user without ROOT access (without developer mode that provides ROOT access). But then the "shell" command and others don't work as if they don't exist (Crosh: Error: unknown command: shell). Does anyone have an updated walkthrough for using the script in 2023?

**Comment by MrChromebox** [comment]
you seem to be confusing two unrelated things here. The 'shell' command only works in a crosh terminal if you're in Developer Mode.  You can only run the script from crosh terminal after running 'shell.' None of that has anything to do with running the script as root.

The instructions for running the script are literally unchanged over the past decade:

* put device into developer mode
* disable hardware WP if needed for function being performed
* open a crosh terminal
* run 'shell'
* run the command to download/run the Firmware Utility Script as per https://mrchromebox.tech/#fwscript
