### ISSUE TITLE
ASUS CN60 UEFIFw: Kodi Freezez after 12Sec

### ISSUE THREAD

**Issue by 12devm** [MrChromebox/scripts#290]
Hi, Asus CN60 ,did the Bios update to UEFI- Thank you for great work. Unfortunately,  video freezes exactly after 12 sec. I'm not sure what info to provide.Kodi-Lbreelec- did all the video upscaling changes etc; reinstalled many times. Please help.I'm not a Linux expert but can do some command line work. Any hints or guidance is much appreciated.Thank you. Dv
[putty_1.log](https://github.com/MrChromebox/scripts/files/11995150/putty_1.log)

**Comment by MrChromebox** [comment]
there's nothing in the log to show a problem, need to look at the kodi log file I guess. I've not used LE myself in many years, so your best bet for support is going to be the LE or Kodi forums. Likely a kernel bug or similar.

**Comment by 12devm** [comment]
> there's nothing in the log to show a problem, need to look at the kodi log file I guess. I've not used LE myself in many years, so your best bet for support is going to be the LE or Kodi forums. Likely a kernel bug or similar.

Thank you. Will do that.

**Comment by MrChromebox** [comment]
Closing as not a script issue
