### ISSUE TITLE
MrChromebox ARM support

### ISSUE THREAD

**Issue by ericcurtin** [MrChromebox/scripts#291]
If we could get UEFI on something like the Qualcomm-based Lenovo Duet 3 which could boot to grub (maybe even install .iso) that would be the dream (could even chainload via u-boot if we wanted). Thanks so much for your efforts btw!

**Comment by ericcurtin** [comment]
I saw you closed an earlier issue on this, feel free to close again I guess, https://github.com/MrChromebox/scripts/issues/159 ... sigh....

**Comment by MrChromebox** [comment]
sorry, there's simply nothing I can do. There is no alternative bootloader to employ
