### ISSUE TITLE
BSOD DRIVER PNP WATCHDOG while trying to boot windows 11 or 10

### ISSUE THREAD

**Issue by coderprogrammer12436** [MrChromebox/scripts#294]
so when i make my usb to boot i boot off it and then like 5-10 minutes its just the loading circle then it gives me the error ive tried a few things but non of them are working any suggestions? my chromebook is the ASUS C523N or C523 im not 100% sure but there you  go

**Comment by MrChromebox** [comment]
this isn't an issue with the script itself; there is already a firmware issue open for this
