### ISSUE TITLE
Home Assistant on chroot?

### ISSUE THREAD

**Issue by abwebc** [MrChromebox/scripts#295]
Can you help with installing Home Assistant OS on chroot by crouton?

On HP Chromebook x360 11 G2 EE | MEEP

without CR50 because i dont have SuzyQable (Suzy Q cable)

**Comment by abwebc** [comment]
Also, can anyone help orderding SuzyQable to Poland from China?
https://detail.tmall.com/item.htm?id=703023036811&skuId=5123592542011&spm=a220l.1.0.0.34fc7f330zK1tY

**Comment by MrChromebox** [comment]
I don't have any experience using crouton.

You can disable the WP on MEEP by booting with the battery disconnected as per https://mrchromebox.tech/#devices
