### ISSUE TITLE
firmware.util.sh no such file or directory 

### ISSUE THREAD

**Issue by ysage96** [MrChromebox/scripts#297]
![image](https://github.com/MrChromebox/scripts/assets/140872434/5caa23fb-d75f-4316-b98b-1c131be46457)
Hi, I’m having an error when trying to download the utility script! I’m doing this using live ubuntu and the chromebook is an Acer CB311-9H Gemini-lake Bobba

**Comment by MrChromebox** [comment]
uninstall snap-based curl, install curl from apt (sudo apt update && sudo apt install curl)
