### ISSUE TITLE
RW_LEGACY bin file has invalid/missing reference for Picasso/Zen2 boards.

### ISSUE THREAD

**Issue by brendangreenley** [MrChromebox/scripts#298]
I was getting a checksum error when trying to update my MORPHIUS board (C13 Yoga) RW_LEGACY firmware despite it working in the past. I decided to see what the actual file/MD5 was resolving to, only to see that the files were not downloading at all and were missing. The checksum error was because neither the bin nor the md5 file are accessible at the path indicated in the script.

Here is the referenced firmware file for the MORPHIUS board:

https://github.com/MrChromebox/scripts/blob/67412af87a918938f1a4f1d1fee7f7e912e21d09/sources.sh#L277

Building the URL manually (https://www.mrchromebox.tech/files/firmware/rw_legacy/BIN_FILE_HERE) works for most boards, resolving a valid bin and md5 file, but not for the bin file referenced in the line above

MORPHIUS RW_LEGACY bin/md5 currently pointed to that do not resolve (404):
https://www.mrchromebox.tech/files/firmware/rw_legacy/rwl_altfw_pco-mrchromebox_20210623.bin
https://www.mrchromebox.tech/files/firmware/rw_legacy/rwl_altfw_pco-mrchromebox_20210623.bin.md5

I see the paths were recently changed with this commit three days ago, and guess it is related: https://github.com/MrChromebox/scripts/commit/278520c5f4330f9cce68fc901d18d3cceda0d857

as both of the below resolve:

https://www.mrchromebox.tech/files/firmware/rw_legacy/rwl_altfw_zen2-mrchromebox_20210623.bin
https://www.mrchromebox.tech/files/firmware/rw_legacy/rwl_altfw_zen2-mrchromebox_20210623.bin.md5

I manually edited the script to point to the old paths and it works as expected. Guessing a PR to revert to the old naming is not the ideal fix, but rather the files should be renamed on the server.

**Comment by MrChromebox** [comment]
fixed
