### ISSUE TITLE
can't use 'sudo' on chromeos 117

### ISSUE THREAD

**Issue by yilili** [MrChromebox/scripts#300]
Sudo commands will not succeed by default.
If you want to use sudo commands, use the VT-2 shell
(Ctrl-Alt-{F2/Right arrow/Refresh}) or build the image with the
login_enable_crosh_sudo USE flag:

$ USE=login_enable_crosh_sudo emerge-$BOARD chromeos-login
or
$ USE=login_enable_crosh_sudo cros build-packages --board=$BOARD

I can't use 'sudo' on chromeos 117
when i enter rhe above two commands,it return:
USE=login_enable_crosh_sudo emerge-$BOARD chromeos-login
bash: emerge-: command not found
USE=login_enable_crosh_sudo cros build-packages --board=$BOARD
bash: cros: command not found

how can i use 'sudo' on chromeos

**Comment by MrChromebox** [comment]
dup of #299
