### ISSUE TITLE
Pixelbook 2017 error installing full rom

### ISSUE THREAD

**Issue by xcpky** [MrChromebox/scripts#301]
![image](https://github.com/MrChromebox/scripts/assets/52552971/28e93e2b-3b7d-43fd-bc6e-08580d7a2635)
before running the script, the system tells me to reboot to get the system update. I didn't reboot and run the script, I got the above error. I thought it may be due to the system update so I rebooted, forgetting to restore the firmware. Then I am left with "Please Insert a Recovery usb stick", and can't boot. The recovery reason is `0x13 / 0x00 RW firmware unable to verify key block`. 

What should I do now and what is the possible cause of the installing error?

**Comment by MrChromebox** [comment]
this was likely caused by not rebooting after disabling WP via CCD
