### ISSUE TITLE
Unable to read current firmware; cannot continue

### ISSUE THREAD

**Issue by deyzi-the-youtuber** [MrChromebox/scripts#302]
Hello. I'm trying to restore my ASUS C204MA Chromebook running Ubuntu, to its default ROM but I keep getting an error that looks something like this:

Unable to read current firmware; cannot continue:

flashrom dc8caac9-dirty on Linux 6.2.0-26-generic (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
ERROR: Could not get I/O privileges (Operation not permitted).
You need to be root.
Error: Programmer initialization failed.

**Comment by HighOnVoltage** [comment]
You could always do it the old fashion way with an SPI ROM adaptor   
[](https://wiki.mrchromebox.tech/Unbricking)

**Comment by PhantomTimed** [comment]
Please disable Secure Boot before running the script.

**Comment by player-k12** [comment]
`sudo su` then run the firmware utility script?

**Comment by Mojr78** [comment]
@deyzi-the-youtuber hi there, plz can you show me how u did it (put Ubuntu on the Chromebook) cuz am not able I removed the screw but it still says Hardware write-protect enabled, cannot flash Full ROM firmware.

**Comment by MrChromebox** [comment]
> @deyzi-the-youtuber hi there, plz can you show me how u did it (put Ubuntu on the Chromebook) cuz am not able I removed the screw but it still says Hardware write-protect enabled, cannot flash Full ROM firmware.

please don't hijack this issue with an unrelated question. WP disablement methods for every supported device are listed on my site
