### ISSUE TITLE
Errors!

### ISSUE THREAD

**Issue by TheEpicTen** [MrChromebox/scripts#303]
So. I was trying to get windows 10 (build 1607) on my Chromebook (Lenovo 300e Gen 2) and it mostly worked, until I got to the step: Where do you want to install windows? No hard drives show up and I can’t find any drivers anywhere for it. Anyone know how I can make the internal drive show up during install?

**Comment by MrChromebox** [comment]
this is not an issue with my script, nor with my firmware. Windows support is available via coolstar.org and the chrultrabook discord server. the TLDR is that your media is not created properly, please see my FAQ page
