### ISSUE TITLE
Remove excess boot devices from boot menu

### ISSUE THREAD

**Issue by TheEpicTen** [MrChromebox/scripts#305]
I have tried to install Fedora WS 38 a few times, and every time it has crashed, or something hasn’t worked. However, I now have about 8 devices in the boot menu named “Fedora”, plus UEFI Shell, and eMMC device. How do I remove these excess fedora drives?

**Comment by TheEpicTen** [comment]
Moved to firmware repo

**Comment by MrChromebox** [comment]
delete all entries?
 * run script, clear UEFI NVRAM
 
delete individual entries?
 * ESC for UEFI Settings on boot
 * Select Boot Manager
 * Select Delete Boot option
 * Select entries to be removed
 * Select Commit changes and exit
 * ESC to back out of UEFI Settings
