### ISSUE TITLE
Asus Chromebook flip 15 cm5500

### ISSUE THREAD

**Issue by tfc31** [MrChromebox/scripts#309]
bonjour j'ai besoin de votre aide svp j'ai le Asus j'ai voulu installer  Windows 10 j'arrive pas  merci d'avance sachant que jarrive pas a faire recovery merci 
![ASUS](https://github.com/MrChromebox/scripts/assets/145364134/fa7715f4-d69c-4887-833c-b6658b2acafb)
!
![Uploading ASUS1.jpeg…]()

**Comment by MrChromebox** [comment]
Windows support is completely handled by coolstar via coolstar.org and the chrultrabook discord server.

**Comment by tfc31** [comment]
Merci de tas réponse si possible me dire comment faire comme vous le voyer sur la photos je peut pas installer update uefi  full rom firmware

**Comment by MrChromebox** [comment]
https://coolstar.org/chromebook/windows-install.html

**Comment by tfc31** [comment]
bonjour j'ai suivi les étape voila se que j'ai comme le devise error et même j'ai rentrer dans recovery utility pour faire pareille je peut même pas restaurer  a l'etat  d'usine  et j'ai regarder sur YouTube d'autre 
![RECOVERY](https://github.com/MrChromebox/scripts/assets/145364134/473ce09c-ffd9-43c1-84b2-71af3b2f75b4)
![9](https://github.com/MrChromebox/scripts/assets/145364134/559aaaef-e9cf-47d9-acbf-78a4fa919bdf)
marque comme hp il faut enlever un vis de sécurité sur la carte mère merci d'avance 
![ASUS](https://github.com/MrChromebox/scripts/assets/145364134/240f1b2d-5d58-473c-bb24-7ed0f615db08)
