### ISSUE TITLE
Unexpected EOL while looking for matching , "

### ISSUE THREAD

**Issue by hnk1** [MrChromebox/scripts#313]
HP Chromebook 14 AMD Careena
Dev mode , ChromeOS version 116.0.5845.210 official
Tried in chronos and terminal with shell 

When trying to use the script : receive following error

![IMG20231001202238](https://github.com/MrChromebox/scripts/assets/6554011/869a611d-caf8-4859-b48e-32a7d3995116)

**Comment by MrChromebox** [comment]
issue has been fixed
