### ISSUE TITLE
Trouble with update seaBIOS to Full UEFI firmware. 

### ISSUE THREAD

**Issue by FrF-sly** [MrChromebox/scripts#316]
Good Afternoon,
First thank you for your job!
I updated my HP for 2-3 years on seabios. It was all fine. Now I try to install UEFI, but receive: "Device: ERROR: unknown or unidentifiable device (NAMI)"
Here must be SONA. Original firmware is not more findable.
Can I say your script, that it is SONA?
I tried all under Linux.

Thank you in advance

dmidecode -s system-product-name returned NAMI too.
dmidecode -s bios-version returned nothing
dmidecode -s bios-release-date returned 09/19/2019

**Comment by MrChromebox** [comment]
hmm, I'll need to modify the script to handle this case - either read the HWID from the GBB under Linux, or handle the NAMI board name better. Let me see which is going to be easier/quicker

**Comment by FrF-sly** [comment]
Thank you!

Now all work fine and I installed  UEFI!
