### ISSUE TITLE
chromebook Lenovo 11e 16GB drive/ chromebook Ultima

### ISSUE THREAD

**Issue by Bobsisf** [MrChromebox/scripts#320]
can i found a solution to flash chrome os on that machine? Tryed live usb, tryed installation linux mint 21.,1 and every time gives me error.

**Comment by Bobsisf** [comment]
here som eoutput from script:`Extracting firmware from recovery USB

cat: /tmp/tmp.F02K5yij7Q/VERSION: No such file or directory
cp: cannot stat '/tmp/tmp.F02K5yij7Q/bios.bin': No such file or directory
rm: cannot remove 'chromeos-firmwareupdate-ultima': No such file or directory
Error: failed to extract firmware from ChromeOS recovery USB
`

**Comment by MrChromebox** [comment]
I'm working on it

**Comment by MrChromebox** [comment]
fixed
