### ISSUE TITLE
RIKKU - missing firmware file

### ISSUE THREAD

**Issue by andmalc** [MrChromebox/scripts#321]
I'm attempting to install the full ROM firmware on my Acer Chromebox CXI2.  Write protect is disabled.  I downloaded and ran the firmware script from within a ChromeOS Guest login.

Error message is: "The script does not currently have a firmware file for your device (RIKKU); cannot continue".

**Comment by MrChromebox** [comment]
sorry about that, fixed

**Comment by andmalc** [comment]
Thanks for the quick fix.
