### ISSUE TITLE
 flashing (UEFI) Full ROM  on  Lenovo ThinkPad C13 Yoga Chromebook (MORPHIUS) causes bricking 	

### ISSUE THREAD

**Issue by gummaph** [MrChromebox/scripts#326]
upon flashing full uefi rom using  MrChromebox’s firmware utility script; post restart we get a black screen and the laptop gets bricked..

**Comment by MrChromebox** [comment]
https://wiki.mrchromebox.tech/Unbricking

also, not a script issue
