### ISSUE TITLE
putting an EOL device back on stock ChromeOS is a bad idea. Flex is the best path forward for Haswell/Broadwell Chromeboxes if you want to keep running ChromeOS.

### ISSUE THREAD

**Issue by WASH90** [MrChromebox/scripts#331]
![WhatsApp Image 2023-11-16 à 16 57 30_e4e462b7](https://user-images.githubusercontent.com/138906291/283986959-53d63ea7-de83-40e4-9534-efab4390201b.jpg)
              putting an EOL device back on stock ChromeOS is a bad idea. Flex is the best path forward for Haswell/Broadwell Chromeboxes if you want to keep running ChromeOS.

What firmware version is listed on the main UEFI screen?

_Originally posted by @MrChromebox in https://github.com/MrChromebox/scripts/issues/246#issuecomment-1419506843_

**Comment by MrChromebox** [comment]
I don't know what you're trying to do here or why you've quoted a comment from another issue. 

The error tells you exactly what the problem is with running the script
