### ISSUE TITLE
CXI2 firmware not working

### ISSUE THREAD

**Issue by itzpere** [MrChromebox/scripts#332]
i brought this unit so i could install linux and run headless server so i did the steps when i got it and because i had some problems with usb i did not backup firmware, also because it said chances of it not working are very low. Anyway when it finished and restarted i was greeted by no display i left it for 10-15 min and still nothing, restarted did the same nothing after that i opened it up downloaded firmware from script sources and flashed it directly to winbond 25q64fv and now it just boot loops (fan is turning on and off constantly like it is shorted somewhere). Anyway i saw the same problem posted on [reddit](https://www.reddit.com/r/chromeos/comments/16xbq19/tinkering_with_an_acer_chromebox_cxi2_with_issues/) like 2 months ago so i posted issue here

**Comment by MrChromebox** [comment]
there's no issue with the firmware, it's been tested on multiple units. What file did you download / what exact command params did you use to flash?
