### ISSUE TITLE
remettre chromeOS sur chomebox sur lequel UIEFI 4.20.0 05/15/2023 #75791 a étè installé

### ISSUE THREAD

**Issue by WASH90** [MrChromebox/scripts#333]
bonjour
J'ai un CHROMEBOOK HP 14a que j'ai intaller une version UIEFI 4.20.0.05/15/2023
et j'aimerais bien remettre la version de base de chromeOS en effet j'ai installé windows sur le (chrombox) hp 14A
mais hélas !! je n'arrive pas a excuter flashroom a travers le script << cd; curl -LOk https://mrchromebox.tech/setup-kodi.sh && sudo bash setup-kodi.sh -k >> sur invitation de commade de UBUNTU il commence le téléchargement mais après j'ai un message d'erreur
ci-joint 
![WhatsApp Image 2023-11-16 à 16 57 30_e4e462b7](https://github.com/MrChromebox/scripts/assets/138906291/b61117c9-b527-49f1-adc1-6c6019bfc359)

j'ai modifie les paramettre du noyau en ajoutant "iomem=relaxed " 
a travers     gedit /etc/default/grub j'ai enregistré 
aprés j'ai effectue la commande sudo update-grub 
ci joint
![WhatsApp Image 2023-11-20 à 19 57 28_73693098](https://github.com/MrChromebox/scripts/assets/138906291/78898a0c-d2f3-4741-9dc6-59775fc42a87) 
j'ai redemarer et j'ai relace la commade  << cd; curl -LOk https://mrchromebox.tech/setup-kodi.sh && sudo bash setup-kodi.sh -k >>
j'ai toujours le meme message d'erreur  
merçi d'avance ...

**Comment by MrChromebox** [comment]
live boot Ubuntu 2304, install curl, run Firmware Utility script nothing else is needed.

Not sure why you're trying to run the deprecated Kodi setup script.

**Comment by WASH90** [comment]
merci de la reponse....
j'ai fais une mise a jour a 23.04
j'ai intallé : curl et apres j'ai exercuté le script:" cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh"
helas j'ai le meme message d'erreur 

merçi d'avance 
![kl](https://github.com/MrChromebox/scripts/assets/138906291/0cb578ec-0eb1-41d9-84ed-2b0ebc10b2db)

**Comment by MrChromebox** [comment]
not sure what the problem is and it's hard to work around using google translate

**Comment by WASH90** [comment]
je ne comprend pas desolé.... comment si prendre avec **goole translate** soit plus explicite stp 
merçi d'avance

**Comment by MrChromebox** [comment]
does `cat /proc/cmdline` show `iomem=relaxed` as one of the parameters?

**Comment by WASH90** [comment]
oui il s'affiche comme l'un des parametre 
ci_joint la photo
![WhatsApp Image 2023-11-23 à 20 41 38_80a4c84a](https://github.com/MrChromebox/scripts/assets/138906291/130497a8-7cf3-48a4-8d04-f6c7c260ec8c)
