### ISSUE TITLE
Low VRAM

### ISSUE THREAD

**Issue by Striker770** [MrChromebox/scripts#334]
Hello, 

Having Lenovo ThinkPad C13 Yoga Chromebook and installed the Mr.Chromebox firmware (Full UEFI). When i tried to install Windows, i saw that the VRAM is just 32MB. Verified it from AMD Control Panel. Is there any way to increase the VRAM?

On my HP 3250U, it has 8GB RAM but the VRAM is 2048MB.

Thanks

**Comment by MrChromebox** [comment]
the VRAM is fixed at 32MB in the firmware and cannot be easily changed

**Comment by Striker770** [comment]
> the VRAM is fixed at 32MB in the firmware and cannot be easily changed

Is it because of this Laptop or all the AMD (Ryzen) firmware from your side has 32MB limit? 

Any workaround for such case?

**Comment by MrChromebox** [comment]
I would need to rebuild a custom AMD firmware component that is loaded by coreboot.

what is the impediment with only 32MB?

**Comment by Striker770** [comment]
> I would need to rebuild a custom AMD firmware component that is loaded by coreboot.
> 
> what is the impediment with only 32MB?

I see. Got macOS installed on it. But it would need a minimum of 512MB VRAM. 2048MB would be great. I'm available on Discord or over email if you want me to do some tests and all.

**Comment by MrChromebox** [comment]
reserving 2GB RAM for VRAM on an 8GB system is very hard to justify; 512MB isn't unreasonable.

> BTW, any specific reasons why you thought to use 32MB? If I'm not wrong your firmware is based on Coreboot right?

I didn't, Google did when they developed the firmware with AMD. My firmware is coreboot + edk2 payload.

**Comment by Striker770** [comment]
> reserving 2GB RAM for VRAM on an 8GB system is very hard to justify; 512MB isn't unreasonable.

I thought the same initially but i have an HP Pavilion with everything stock (BIOS) and it has only 8GB RAM but still the VRAM is 2048MB which was way much surprising to me. 

> I didn't, Google did when they developed the firmware with AMD. My firmware is coreboot + edk2 payload.
Hmm. I see. Can we make some progress on this issue? 512MB VRAM would do the job! Let me know what do you need. Happy to contribute if you have any donation link.

Thanks again for this wonderful project!

**Comment by MrChromebox** [comment]
> Hmm. I see. Can we make some progress on this issue? 512MB VRAM would do the job! Let me know what do you need. Happy to contribute if you have any donation link.

I'll try to do this over the weekend, a bit tied up with holiday stuff ATM. There's a paypal donate link on my site at the bottom of the nav menu ;-)

**Comment by Striker770** [comment]
> > Hmm. I see. Can we make some progress on this issue? 512MB VRAM would do the job! Let me know what do you need. Happy to contribute if you have any donation link.
> 
> I'll try to do this over the weekend, a bit tied up with holiday stuff ATM. 

Sure. I'm excited. 

Happy Thanksgiving :)

> There's a paypal donate link on my site at the bottom of the nav menu ;-)

Thank you

**Comment by MrChromebox** [comment]
@Striker770 please DM or ping me on discord

**Comment by Striker770** [comment]
> @Striker770 please DM or ping me on discord

Done. Thank You

**Comment by MrChromebox** [comment]
@Striker770 actually I just updated all of the Picasso images with a fix for the Athlon 3150C variants, and fixed 512MB VRAM as well. So just update from the script and see how that works for you

**Comment by Striker770** [comment]
> @Striker770 actually I just updated all of the Picasso images with a fix for the Athlon 3150C variants, and fixed 512MB VRAM as well. So just update from the script and see how that works for you

OMG. Going to try it now and report. Meanwhile can you add me on the Discord please? Primeee#4056 is my username. 

Thanks again!

**Comment by Striker770** [comment]
@MrChromebox So, i flashed using the new script using Ubuntu and i literally tried everything and there is no sign of display, nothing. The power LED flashes white and that's it. Seems like firmware got it broken. Any ways to recover?

**Comment by Striker770** [comment]
@MrChromebox Okay, it's back to life. I can see the new version!

Reporting in a couple of minutes.

**Comment by Striker770** [comment]
@MrChromebox And it's a SUCCESS!

Well done. Thank you so much. However, seems like it needs like 1GB VRAM for the proper operation as the system restarts abruptly.

**Comment by MrChromebox** [comment]
@Striker770 then I'll need to do a one-off firmware for you, HMU in the AMD-picasso channel on the chrultrabook discord and I'll do that

**Comment by Striker770** [comment]
> @Striker770 then I'll need to do a one-off firmware for you, HMU in the AMD-picasso channel on the chrultrabook discord and I'll do that

Can you please send me the invite? Not sure where i can find the link to join!

**Comment by MrChromebox** [comment]
https://discord.gg/8ZwD4E3n

**Comment by Striker770** [comment]
> https://discord.gg/8ZwD4E3n

Thank you!
