### ISSUE TITLE
Asus c200 chromebook can't install firmware utility script 

### ISSUE THREAD

**Issue by muhaabaminu** [MrChromebox/scripts#338]
I have asus c200 chromebook when i tried to install firmware utility using mrchromebox.tech command it keep "curl: (28) operation time out after 300448 milliseconds" after taking long time and i have a good internet connection please help

**Comment by HighOnVoltage** [comment]
Check if WPS is disabled,
see: [(https://www.reddit.com/r/chrubuntu/comments/7298d5/installing_linux_on_asus_c200_chromebook/)]

**Comment by muhaabaminu** [comment]
Yeah, Thank you HighOnVoltage i already solved the problem is the faulty of my network.
