### ISSUE TITLE
Morphius Lenovo ThinkPad C13 old firmware Trackpoint NoT working

### ISSUE THREAD

**Issue by bparihar** [MrChromebox/scripts#340]
i already flashed the old [morphius] firmware which a holding a bug for Trackpoint
now my Trackpoint ia not working can any one guide me with reflashing the new firmware on my C13 [morphius] I'm on Windows now 

Regards
Bhavesh

**Comment by MrChromebox** [comment]
you cannot use the trackpoint-enabled firmware with Windows currently, due to incompatibilities with coolstar's Windows drivers

**Comment by bparihar** [comment]
Can You guide me how can i reflash the right firmware again and from which Operating system i can do that .

Thankyou

**Comment by bparihar** [comment]
> you cannot use the trackpoint-enabled firmware with Windows currently, due to incompatibilities with coolstar's Windows drivers

Can You guide me how can i reflash the right firmware again and from which Operating system i can do that .

Thankyou

**Comment by MrChromebox** [comment]
there's no guide, you boot Linux, run the script, and when prompted choose the TP enabled version
