### ISSUE TITLE
Elan Touchpad on Linux Ubuntu / Kernel 6.5.x / Kernel 6.x / Kernel 6.7.x

### ISSUE THREAD

**Issue by jonas5** [MrChromebox/scripts#345]
Bios ver: 4.22.0-5

I did a bios update yesterday on my Lenovo Morphius C13.

Got some issues booting kernel into newer versions. This was working on 4.21 November release 

Got a stack trace photo from kernel output.
![IMG_20240114_132929](https://github.com/MrChromebox/scripts/assets/14141355/3bd0e8fa-ad33-4bb7-a7c2-322e368029e3)

The laptop still boots in kernel 6.2, newer kernels have issues with the Touchpad and most other devices loaded. It won't even load any network or WiFi.

Hope this helps.

**Comment by MrChromebox** [comment]
nothing changed at all between the 4.21.x and 4.22.0 release w/r/t the touch input devices, i2c, or anything like that. The ACPI tables should be almost identical. This seems like a kernel issue to me

**Comment by jonas5** [comment]
Thanks for your response, This could be a kernel issue.

I installed 6.5.x and 6.6.9 / 6.7 before I did a bios update.
The issue only occurred after the bios update.
Never the less, kernel 6.2.x is working like a charm.

**Comment by jonas5** [comment]
Is there any possibility to get access to older releases to verify?

**Comment by Firminator** [comment]
@jonas5 I also noticed no touchpad in kernel 6.5
5.15 LTS works though. Haven't tried 6.6 or 6.2 yet.

**Comment by MrChromebox** [comment]
closing since this is not a script issue. OS issues are handled by the chrultrabook project
