### ISSUE TITLE
ChromeOS Firmware Utility Script Moved Permanently 

### ISSUE THREAD

**Issue by AdisaGbenga** [MrChromebox/scripts#346]
I am trying to download ChromeOS Firmware Utility Script for my acer 731T Chromebook with the link provided in https://mrchromebox.tech/#fwscript but wasn't downloading.

Then I tried curl -I mrchromebox.tech/firmware-util.sh 

and below was the response I got

HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://mrchromebox.tech/firmware-util.sh
Connection: close

**Comment by MrChromebox** [comment]
> but wasn't downloading.

this isn't useful for diagnosing the issue.

`curl -LO https://mrchromebox.tech/firmware-util.sh` is the correct command and is verified working
