### ISSUE TITLE
Problem with Firmware Utility Script // asus chromebook CX34

### ISSUE THREAD

**Issue by jigirniut** [MrChromebox/scripts#347]
![1705489932084](https://github.com/MrChromebox/firmware/assets/156908054/07b8028f-af8a-4b62-b53c-c2c42e6f5802)
Google_Marasov.14505.527.0
asus chromebook CX34

**Comment by MrChromebox** [comment]
this appears to be an issue with the UFS-equipped devices

**Comment by MrChromebox** [comment]
issue has been fixed, but UFS devices are having issues with the UEFI firmware so I wouldn';t recommend flashing just yet

**Comment by MrChromebox** [comment]
a SuzyQ cable is the only way to disable WP on the CX34. Opening the device will do nothing at all.

I'd also advise you to check the chrultrabook docs and forum to see how well your device is supported for the OS you want to run. Firmware support is only half the equation. If you have further questions I'd advise asking there as this is an issue tracker, not support forum.
