### ISSUE TITLE
I get this error, every time I try to run the script.

### ISSUE THREAD

**Issue by hansoppa** [MrChromebox/scripts#349]
![Screenshot 2024-01-19 3 09 24 AM](https://github.com/MrChromebox/scripts/assets/157101519/f5753cff-fccc-4155-bc50-fc09b7956298)

![Screenshot 2024-01-19 3 11 05 AM](https://github.com/MrChromebox/scripts/assets/157101519/2447e477-f4cb-4537-844a-527fd41d60c3)

![Screenshot 2024-01-19 3 11 58 AM](https://github.com/MrChromebox/scripts/assets/157101519/92accad8-f229-461a-adca-49eda34e04cb)

**Comment by hansoppa** [comment]
I have no idea what to do, I've been looking everywhere for a solution.

**Comment by hansoppa** [comment]
I'm also really new to chromebook, all I'm trying to do, is to get windows software. I've been at it for 2 weeks now :(
Also yes, CR50. If that even means anything.

**Comment by hansoppa** [comment]
I am also in developer mode with WP disabled.
![Screenshot 2024-01-19 3 15 24 AM](https://github.com/MrChromebox/scripts/assets/157101519/396e03b3-941b-4d8e-81d0-1dac2c5e863c)

**Comment by Firminator** [comment]
Try pinging raw.githubusercontent.com to see if you connectivity.

**Comment by NaadeemKhali** [comment]
I'm facing the same issue even though my device is supported "Grabbiter"

**Comment by hansoppa** [comment]
Hello! I got past this issue somehow. I am a complete novice at this, but I am now stuck on 'select a driver to install'. Hence, I am trying to install Windows 11 on my Lenovo Gaming 16". For some reason the intel drivers I put on my USB were incompatible with my device, so I am stuck in a loop for trying to find solutions for this situation.
