### ISSUE TITLE
Error Downloading one or more required files; cannot continue 

### ISSUE THREAD

**Issue by NaadeemKhali** [MrChromebox/scripts#354]
while my Chrome book "Grabbiter"is valid for the both firmware but somehow I get this error. 
I use VT-2,not the Linux console.
the "Error Downloading one or more required files; cannot continue " comes after Mrchomebox firmware Utility script starting up 

I did turn off verification

what can I do?
 Thank you !!

**Comment by MrChromebox** [comment]
perform a USB recovery and try again
