### ISSUE TITLE
hp x360 14c (DRAGONAIR) has no available options despite being listed

### ISSUE THREAD

**Issue by BetaDoggo** [MrChromebox/scripts#355]
I think the Full Rom option should be supported according to the site but it's greyed out. Write protection is disabled and I'm seeing no other errors.

The script lists the board as DRAGONAIR-TMTX. I'm wondering if this a unique board revision that isn't supported. I'm not seeing extensions at the ends of any other board names on the list so I assumed that they didn't matter.

I was able to edit the comet lake list so that the option became available, but that might not be a good idea.

**Comment by MrChromebox** [comment]
fixed
