### ISSUE TITLE
MAGLITH - missing firmware file

### ISSUE THREAD

**Issue by InvalidFish** [MrChromebox/scripts#356]
Was attempting to install a full rom install on my Acer Chromebook 511, Attempted to use the firmware-util.sh with WP disabled and after pressing Y to get pass to ChromeOS will no longer be bootable warning. I receive this error after I press enter
"The script does not currently have a firmware file for your device (MAGLITH); cannot continue"

**Comment by MrChromebox** [comment]
sorry about that -- added!

close/retry the script in a few mins and should be there
