### ISSUE TITLE
Problem installing full rom firmware 

### ISSUE THREAD

**Issue by cool-dev-code** [MrChromebox/scripts#360]
When i try to Install Full Rom Firmware
this comes after downloading

> Firmware download checksum fail; download corrupted, cannot flash.

help me 
Chromebook Acer C720

**Comment by MrChromebox** [comment]
well, either the download failed for some reason, in which case you should try again, or you're running some forked version of my script that's pointing to old files that don't exist. Post pics of the main script menu and the error itself

**Comment by cool-dev-code** [comment]
It was a network issue. I changed the wifi and the problem is solved. Now, I am installing ChromeOS Flex.
Thank you for what you did 💖❤️. Really appreciate your work
