### ISSUE TITLE
install uefi firmware disable error

### ISSUE THREAD

**Issue by aparrilla** [MrChromebox/scripts#363]
![IMG_20240210_125351_631](https://github.com/MrChromebox/scripts/assets/17971743/70fa1bd4-5af3-41a6-a4f9-e95db4e41ab3)

Can you help me? i want to install win10

**Comment by aparrilla** [comment]
i have backup firmware

**Comment by MrChromebox** [comment]
as I replied via email, you managed to mess up the HWID and so the script can't detect your device.

use function 4, set HWID, to set it to: ASUKA ABC-123

then reboot and re-run the script, should detect it properly. 

Windows install instructions, drivers, etc are available on coolstar.org and doc.chrultrabook.com / forum.chrultrabook.com
