### ISSUE TITLE
a bug that could stop chrome os from booting when reinstalling stock firmware

### ISSUE THREAD

**Issue by Mrnermaler** [MrChromebox/scripts#364]
so when you run cd; curl -LOk mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh and then use your chrome os recovery drive  it will come up with your hardware ID is malformed this happens after you revert back to chrome os 

so  my Chromebooks board name is on mutable Chromebook relm

**Comment by MrChromebox** [comment]
a malformed HWID doesn't stop ChromeOS from booting. The script has no way of providing a valid HWID from a recovery image firmware.
