### ISSUE TITLE
ERROR message 'iomem=relaxed'  ASUS CN60 chromebox

### ISSUE THREAD

**Issue by StarMusa88** [MrChromebox/scripts#365]
Thanks for your amazing work ...Everything is working no issues since I installed MrChromebox on my ASUS CN60 chromebox. But I also recently installed Ubuntu 23.04 and i ran the script from the firmware guide on MrChromebox.tech website.
 ( cd; curl -LOk mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh) 

but I keep getting error  message when trying to run the script ..

You may need to add 'iomem=relaxed'  to your kernel parameters or trying running from a live USB with a more permissive kernel (eg, Ubuntu 23.04+)

Can't seem to figure out how to fix it, I'm just trying to see if I can update the Bios. Any help would be greatly appreciated.

**Comment by MrChromebox** [comment]
you should have no issues running the script on Ubuntu 23.04, it works fine on a live USB here. If the installed version behaves differently, you might need to do what the error says -- add 'iomem=relaxed' to your kernel boot parameters.

PS - you don't need the 'k' in the script command, not sure why you're using it.

**Comment by StarMusa88** [comment]
Hi,

 I'm still getting error message after adding 'iomem=relaxed' to kernel parameters,  I also upgraded to Ubuntu  23.10. 


lsb_release -a  15:50:17 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic


cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-6.5.0-17-generic root=UUID=4a46ba30-61de-45cb-8ab1-13669fffa628 ro iomem=relaxed quiet splash vt.handoff=7

cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh





MrChromebox Firmware Utility Script starting up

Downloading supporting files...

Downloading required tools...

Getting device/system info...

Flashrom is unable to read current firmware; cannot continue:

flashrom 1.4.0-devel on Linux 6.5.0-17-generic (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
ERROR: Could not get I/O privileges (Operation not permitted).
Your kernel may prevent access based on security policies.
Issue a 'dmesg | grep flashrom' for further information
Error: Programmer initialization failed.

You may need to add 'iomem=relaxed' to your kernel parameters,
or trying running from a Live USB with a more permissive kernel (eg, Ubuntu 23.04+).

See https://www.flashrom.org/FAQ for more info.

**Comment by MrChromebox** [comment]
please try with a 2304 live USB and let me know if you have an issue there

**Comment by StarMusa88** [comment]
I just tried it again on 23.04 USB live same error message..
all good it was worth a try. thanks again

**Comment by MrChromebox** [comment]
this doesn't make any sense. I just booted Ubuntu 23.04 Live USB, installed curl, and ran the script without issue on my CN60

![Screenshot from 2024-02-14 14-33-31](https://github.com/MrChromebox/scripts/assets/948902/fd496a6e-0b6b-47b0-91c5-6f7d2f32b7cf)

**Comment by EpicPotatohead** [comment]
This started happening to me a week or two (or three...) ago on a GALLOP chromebook running Fedora 39. Perhaps something has changed with the kernel? If I reboot and add 'iomem=relaxed' to the kernel options in grub, firmware-util.sh runs normally. If I don't add that option, I get this:

```MrChromebox Firmware Utility Script starting up

Downloading supporting files...

Downloading required tools...

Getting device/system info...

Flashrom is unable to read current firmware; cannot continue:

flashrom 1.4.0-devel on Linux 6.7.4-200.fc39.x86_64 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Cannot open file stream for /dev/mtd0
coreboot table found at 0x76b58000.
Found chipset "Intel Jasper Lake".
Enabling flash write... Warning: Setting BIOS Control at 0xdc from 0x8b to 0x89 failed.
New value is 0x8b.
Error accessing SPIBAR, 0x1000 bytes at 0x00000000fe010000
/dev/mem mmap failed: Operation not permitted
FAILED!
FATAL ERROR!
Error: Programmer initialization failed.

You may need to add 'iomem=relaxed' to your kernel parameters,
or trying running from a Live USB with a more permissive kernel (eg, Ubuntu 23.04+).

See https://www.flashrom.org/FAQ for more info.
```

Fantastic work, btw. I've been running Fedora on this thing for many months without issue. It's much more useful to me than ChromeOS and it works great. This is the first problem I've run into (sound doesn't work, but I don't really care), and so far the iomem=relaxed workaround works.

**Comment by StarMusa88** [comment]
I'm using dual boot could that be what's causing this issue?

**Comment by StarMusa88** [comment]
![20240216_021848.jpg](https://github.com/MrChromebox/scripts/assets/142222631/16f6683a-8392-4354-9710-ee20d962a5d4)

![20240216_022016.jpg](https://github.com/MrChromebox/scripts/assets/142222631/bf9cbb00-2a6b-4776-b383-68563cf24629)

![20240216_021901.jpg](https://github.com/MrChromebox/scripts/assets/142222631/e8006e9d-de6b-4674-ad90-cea3d9972221)

**Comment by StarMusa88** [comment]
And this time with adding iomem=relaxed. 


![20240216_024124.jpg](https://github.com/MrChromebox/scripts/assets/142222631/eca74877-7a5f-4fb2-8d73-b63dfd173f03)

![20240216_024111.jpg](https://github.com/MrChromebox/scripts/assets/142222631/c089de98-e0b8-4bfe-8457-79b06eafe9f6)

**Comment by StarMusa88** [comment]
Is there another way to update the bios?


![20240216_024640.jpg](https://github.com/MrChromebox/scripts/assets/142222631/c952d3c1-6a0c-4900-96e3-8b26ecbd8bf3)

**Comment by MrChromebox** [comment]
@EpicPotatohead please see the chrultrabook docs for info on getting audio to work under Linux

@StarMusa88 seems like something must have changed in the default kernel config. Try using 22.04 instead? you'll likely need to install curl via apt first.

**Comment by StarMusa88** [comment]
Hi @MrChromebox - I have an update, I finally figured what the issue was . I had secure boot enabled that's what was preventing the script from executing.  I was able to update the bios with no error message...Thanks again for your help much appreciated.

**Comment by MrChromebox** [comment]
@StarMusa88 thanks for circling back :)
