### ISSUE TITLE
Add me_cleaner option to firmware-util.sh

### ISSUE THREAD

**Issue by souchikjoardar201** [MrChromebox/scripts#394]
Add option to include running me_cleaner onto supported models in `firmware-util.sh` menu
- Detect if firmware is supported just like if WP
  - Run *me_cleaner* on `$coreboot_file` before flashing if flag was selected   

> https://github.com/corna/me_cleaner/wiki/Internal-flashing-with-coreboot

**Comment by MrChromebox** [comment]
I will not be doing this for several reasons:

1) Chromebooks have locked IF/ME regions, the ME cannot even be read from a live/running system unless the IFD is modified via external flashing. The link you provided does not apply to devices which ship with coreboot, it assumes you have flashed coreboot and an unlocked IFD.,

2) Using ME cleaner is completely unnecessary on devices without AMT

3) Disabling the ME via HECI or soft-disable command from coreboot is just as effective
