### ISSUE TITLE
Multilaser M11HC PC915 FIRMWARE recovery

### ISSUE THREAD

**Issue by rasppinha** [MrChromebox/scripts#395]
I have a Chromebook that was company locked. I installed the mrchromebox firmware via the eprom burner, but I'm having problems with the operating systems. and I wanted an original firmware without the lock. I tried with the script utility but my fw is blocked and I have already done all the possible tutorials to unlock it and I was unable to do so. Is there any way to download and record via eprom?

**Comment by rasppinha** [comment]
GARG360 BOARD IS DALI9BMB6D0 REV:D

**Comment by MrChromebox** [comment]
see: https://github.com/coreboot/coreboot/tree/main/util/chromeos

download crosfirmware.sh and run it: `bash crosfirmware.sh garg360`

**Comment by Andrade684** [comment]
> I have a Chromebook that was company locked. I installed the mrchromebox firmware via the eprom burner, but I'm having problems with the operating systems. and I wanted an original firmware without the lock. I tried with the script utility but my fw is blocked and I have already done all the possible tutorials to unlock it and I was unable to do so. Is there any way to download and record via eprom?

You cabd sen-me this EPROM please, If some one have please??
