### ISSUE TITLE
Download Full ROM takes forever... Unable to install the UEFI firmware

### ISSUE THREAD

**Issue by skadop** [MrChromebox/scripts#396]
When I try to install the Full ROM Firmware, the command "cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh" and the command "cd; curl -LOk mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh" work well until I accept the terms, then the promp says that it is downloading the "coreboot_edk2-celes-mrchromebook_20240416.rom". But, it can't download the file. I tried to use other line on internet, but it didn't work either

**Comment by skadop** [comment]
The screen just shows that is downloading and the name os the file "coreboot_edk2-celes-mrchromebook_20240416.rom", but it takes forever

**Comment by MrChromebox** [comment]
I'm not seeing any issues on the server side or from my location (USA), where are you located?

**Comment by skadop** [comment]
![20240424_135832](https://github.com/MrChromebox/scripts/assets/168005175/ee929c75-b226-4d76-8323-5f14eff3b759)
I'm in Brazil.

**Comment by skadop** [comment]
Could you send me the .rom file, so I can update the firmware manually?

**Comment by skadop** [comment]
coreboot_edk2-celes-mrchromebook_20240416.rom

**Comment by skadop** [comment]
I tried to use a us VPN, but the waiting is still a thing

**Comment by MrChromebox** [comment]
[coreboot_edk2-celes-mrchromebox_20240416.zip](https://github.com/MrChromebox/scripts/files/15098498/coreboot_edk2-celes-mrchromebox_20240416.zip)

**Comment by skadop** [comment]
Sr. I did a hard reset, and tried again.. so it now worked. Thank you, again
![Uploading 20240424_155833.jpg…]()

**Comment by raimondtovar** [comment]
buenas noches necesito por favor alguien me ayude necesito la rom uefi para la placa treeya coreboot_edk2-treeya-mrchromebox_20251130.rom
