### ISSUE TITLE
ThinkCentre M70q chromeos locked

### ISSUE THREAD

**Issue by bparihar** [MrChromebox/scripts#397]
I have recently purchased ThinkCentre M70q with locked ChromeOS unable to unlock it by any method please help 

I'm already a user of  unlocked Chromebook windows user thanks to @MrChromebox for that support.

**Comment by MrChromebox** [comment]
this isn't really an issue with my firmware or something my script can do. The best option I can offer is for you to flash the UEFI firmware image directly using an external programmer, following the instructions in my unbricking guide: https://wiki.mrchromebox.tech/Unbricking. a SuzyQ will not work here since the CCD is locked out by virtue of the device being managed

**Comment by bparihar** [comment]
@MrChromebox Thanks for understanding the situation please share the UEFI Firmware for Lenovo M70Q So i can unlock the device

**Comment by MrChromebox** [comment]
the unbricking guide linked above tells you how to get the current download links :)

**Comment by bparihar** [comment]
Hello There @MrChromebox Lenovo M70q is not present in the list where can i find the firmware

**Comment by MrChromebox** [comment]
> Hello There @MrChromebox Lenovo M70q is not present in the list where can i find the firmware

You mean the M60q, right? Google turns up nothing for a M70q Chromebox

https://mrchromebox.tech/#devices lists the name for the M60q as KINOX. The script provides a download for this board

**Comment by bparihar** [comment]
@MrChromebox  i mean Lenovo M70Q its this machine 
https://www.lenovo.com/ca/en/p/desktops/thinkcentre/m-series-tiny/thinkcentre-m70q/wmd00000405?orgRef=https%253A%252F%252Fwww.google.com%252F

locked as chromeos and showing some Amazon ChromeOS Admin locked

**Comment by MrChromebox** [comment]
@bparihar that's not a ChromeOS device, nothing we can do to help

**Comment by MrChromebox** [comment]
> It's runing on Chromium 132.0.6834.214 csos-release-channel iridium test

that's an Amazon device running a fork of  ChromiumOS, it's not a ChromeOS device and nothing I can do / not supported
