### ISSUE TITLE
HP CHROMEBOOK C640 G2 NOT BEING BOOTED IN WINDOWS

### ISSUE THREAD

**Issue by rosanyadav08** [MrChromebox/scripts#406]
After flashing chrome os , when we try to boot it in UEFI method the storege / in cheap ssd not showing , what to do please can you guide ,
Please help me with your precious time

**Comment by MrChromebox** [comment]
I don't understand the issue, can you attach a picture?

**Comment by rosanyadav08** [comment]
![IMG_20240606_133211.jpg](https://github.com/MrChromebox/scripts/assets/160944426/51bb5128-fe53-4d11-812b-2197b609a969)

![IMG_20240606_133207.jpg](https://github.com/MrChromebox/scripts/assets/160944426/a14908f4-ec76-43a0-b678-dbecb8be85c8)

I don't know what to do for this

**Comment by rosanyadav08** [comment]
I am trying to make it in windows 11 but because of this error i am faceing issues

**Comment by MrChromebox** [comment]
does your internal storage drive show up in the boot menu list?
what is the board name shown at the top of the UEFI settings screen?
can you boot a Linux USB and capture a cbmem log?

**Comment by rosanyadav08** [comment]
Board name -  elemi 
It doesn't shows and storage drives in boot  list

**Comment by MrChromebox** [comment]
sounds like an eMMC driver issue in edk2, unless something changed on the coreboot side. Do you have a NVMe drive you can pop in to test?

**Comment by rosanyadav08** [comment]
The laptop doesn't have any slot in board for ssd

**Comment by MrChromebox** [comment]
are you sure? HP's specs suggest otherwise

**Comment by rosanyadav08** [comment]
I am not sure about it but i can share you its motherboards image

**Comment by rosanyadav08** [comment]
Actually i new in this field , i don't have much idea

**Comment by MrChromebox** [comment]
> I am not sure about it but i can share you its motherboards image

please do

**Comment by rosanyadav08** [comment]
![IMG_20240607_110404.jpg](https://github.com/MrChromebox/scripts/assets/160944426/8cc2af08-d8fe-449b-ad2c-6cb7b9c96feb)

![IMG_20240607_110510.jpg](https://github.com/MrChromebox/scripts/assets/160944426/fb8f899a-f42d-4d55-8f24-4e34100785cf)

**Comment by rosanyadav08** [comment]
Can you say what to do next

**Comment by MrChromebox** [comment]
do you have a SuzyQ cable for debugging? If not, nothing I can do

**Comment by MrChromebox** [comment]
closing as not a script issue
