### ISSUE TITLE
How do I login to non-root user in chromebook

### ISSUE THREAD

**Issue by sceneturkey** [MrChromebox/scripts#408]
I'm trying to use the firmware utility script on my Chromebook to install gallium os and have access to Chronos on VT2 console, but it says to use a non-root user. I have no idea how to login to my normal account on terminal or how to make a non-root account to run the script. How can I accomplish this?

**Comment by MrChromebox** [comment]
as per the instructions on my site, you login with user 'chronos' and no password

**Comment by nathblade16** [comment]
chronos is the correct login but I do have to warn you that galliumOS is unmaintaned, install something like fedora or for an ultra lightweight distro use arch, I have arch on mine with the sway window manager
