### ISSUE TITLE
Relies on WP switch when it should be relying on WP ranges

### ISSUE THREAD

**Issue by PeapGit** [MrChromebox/scripts#411]
Chrome OS has a WP switch and WP ranges. The difference between the 2 is one tells how much you can manipulate. But you can have WP ranges at 0, 0 which has WP off while WP switch is on. You can still manipulate WP things but you can't change WP ranges. I have verified this by using the old GBB flag script which doesn't check for WP. The firmware utility you created only checks for the WP switch. It should check for the ranges.

**Comment by PeapGit** [comment]
The command to see this is `flashrom --wp-status`

**Comment by MrChromebox** [comment]
no, the script checks what it needs to.  If checking the range were sufficient, then I'd do it -- but it's not.
