### ISSUE TITLE
Image size doesn't match the expected size

### ISSUE THREAD

**Issue by Shinji321-123** [MrChromebox/scripts#415]
Hello, I have a problem when trying to Install Full ROM Firmware on my Chromebook, it puts me an error saying :

Error : Image size (8388608 B) doesn't match the expected size (16777216 B) !
FAILED

**Comment by MrChromebox** [comment]
I'm going to need to know what device you're using, and what file name the script is downloading

**Comment by Shinji321-123** [comment]
Thanks for responding, it's an Asus Chromebook CX1400CNA, for the file name where can i see it ?

**Comment by MrChromebox** [comment]
before you press a key to see the flashrom error, the script shows the name of the file it's downloading as part of the flashing process. Also show me the script main menu screen please

**Comment by Shinji321-123** [comment]
Here they are
![IMG_20240620_165847](https://github.com/MrChromebox/scripts/assets/173372429/6d7f7ae8-668b-4d26-8f78-12dea5fe9363)
![IMG_20240620_165824](https://github.com/MrChromebox/scripts/assets/173372429/756308a1-344f-4643-9998-e6a9ffeae521)

**Comment by MrChromebox** [comment]
so here is the problem -- you or someone else changed the HWID on the device, and now the script thinks you have a different device than you actually have. Why was that done? SMH. Good way to potentially brick your device.

So, let's do this:
- select option 4 - set HWID
- set the HWID (exactly) to: RABBID EFA-123
- reboot
- re-run the script
- verify your device is identified correctly by the script in the menu.

I also don't understand why you'd run the script, see that it misidentifies your device as a Toshiba Chromebook 2, and proceed anyway. Sigh.

**Comment by Shinji321-123** [comment]
Maybe I made an error while reinstalling ChromeOS on my computer, but now it works, thank you so much !
