### ISSUE TITLE
pixelbook go restore

### ISSUE THREAD

**Issue by flymzero** [MrChromebox/scripts#416]
i want restore but get problem

![wx_camera_1719065411961.jpg](https://github.com/MrChromebox/scripts/assets/13290769/321a13eb-ccf1-4c89-95af-e146fc8cc663)

**Comment by nathblade16** [comment]
DO NOT REBOOT YOUR CHROMEBOOK, you should probably put uefi rom back on there so you can restart and have it actually turn on and after a bit mrchromebox might respond, this is just advice from someone who knows a bit about these scripts and stuff and can't fully resolve this issue

**Comment by MrChromebox** [comment]
agreed, I would reflash the UEFI firmware here before rebooting

**Comment by zzup110** [comment]
I also encountered this problem on Pixelbook go(2019) ATLAS

**Comment by flymzero** [comment]
> I also encountered this problem on Pixelbook go(2019) ATLAS

I use another computer to compulsively brush bios

**Comment by clearc352** [comment]
> > I also encountered this problem on Pixelbook go(2019) ATLAS
> 
> I use another computer to compulsively brush bios
can you provide some details? I have the same problem.
