### ISSUE TITLE
SCRIPT NOT WORKING

### ISSUE THREAD

**Issue by Ismo404** [MrChromebox/scripts#420]
I was trying to restore my chromebook to its original state, i got an Asus c423na-eb0287.
The problem comes when i boot my pc into the live usb and run `cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh` it just give me an error saying that it couldn’t connect to chromebox.tech server even though i was connected to my wifi.
does anyone know how to resolve that?

screenshot: 
![image](https://github.com/user-attachments/assets/44ce8c1f-477c-4d38-b1b2-94a809ca56bf)

**Comment by clm1919** [comment]
does your live USB have a firewall on by default?  it might be blocking port 80

what happens when you try  "ping mrchromebox.tech"

**Comment by MrChromebox** [comment]
> does anyone know how to resolve that?

typos are a bitch
