### ISSUE TITLE
problem could not resolve to host 

### ISSUE THREAD

**Issue by tycoonz123** [MrChromebox/scripts#427]
chronos@localhost / $ cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh
curl: (6) Could not resolve host: mrchromebox.tech

i have this problem

**Comment by player-k12** [comment]
internet issue

**Comment by heis-scuba** [comment]
Hey so that means that the wifi isn't connected to laptop or that the cable for the wifi underneath laptop cover is disconnected ? What to do if the URL isn't working on my Notebook XE513C24 please help have to use my laptop for my classes and am in need of what I should do or type in next
