### ISSUE TITLE
It is impossible to return to the standard firmware

### ISSUE THREAD

**Issue by Vany913** [MrChromebox/scripts#430]
I want to go back to stock firmware, I lost my old firmware. Here are my specs.

![17300213901106856469467019415816](https://github.com/user-attachments/assets/d19ecae0-3c34-4f81-bd45-13d6406105cd)

I used the script in the sequence:
 Restore Stock Firmware>yes>yes>use recovery usb>my flash

result in the photo :(

![17300214355851649354050846953462](https://github.com/user-attachments/assets/4e331563-ff82-4451-a344-63e07079900d)

**Comment by MrChromebox** [comment]
Going back to stock firmware on devices which are past EOL is not supported by the script and not recommended at all.

What are you trying to accomplish exactly?

**Comment by Vany913** [comment]
I understand that my device is not supported. I want to go back to factory firmware to install rw_legacy. But I can't because I didn't understand how important it was to save the old firmware file😓

**Comment by Vany913** [comment]
I understand that my device is not supported. I want to go back to factory firmware to install rw_legacy. But I can't, because I didn't understand how important it was to save the old firmware file😓

**Comment by Vany913** [comment]
What are my options?

**Comment by Vany913** [comment]
What are my options for this?

**Comment by MrChromebox** [comment]
download this, extract zip, copy to USB, use script to t restore. This is the stock firmware with RW_LEGACY firmware pre-packed, and the flags set to boot to RW_LEGACY automatically.

[coreboot-Google_Ultima.7287.131.63_with_rwl.zip](https://github.com/user-attachments/files/17535218/coreboot-Google_Ultima.7287.131.63_with_rwl.zip)

**Comment by Vany913** [comment]
Yes, it worked☺️ Thank you! P.S. maybe it will be useful to someone else?

**Comment by Vany913** [comment]
Sorry, I was able to set rw_legacy but if I press ctrl+l nothing happens

**Comment by MrChromebox** [comment]
did you perform a ChromeOS USB recovery? If so, you erased the RW_LEGACY firmware which I preloaded for you

**Comment by Vany913** [comment]
I must have done everything wrong, what sequence of actions should I have done?

**Comment by Vany913** [comment]
I selected the item firmware from a flash drive

**Comment by MrChromebox** [comment]
> I must have done everything wrong, what sequence of actions should I have done?

restore firmware using the file I provided

reboot

that's it. the firmware is set to boot from RW_LEGACY by default

**Comment by Vany913** [comment]
Can I update the file you provided according to the guide? https://docs.chrultrabook.com/docs/firmware/manually-flashing.html

**Comment by MrChromebox** [comment]
if you are now able to boot ChromeOS, you can manually flash just the RW_LEGACY part of that file:

`sudo flashrom -p internal -w coreboot-Google_Ultima.7287.131.63_with_rwl.bin -i RW_LEGACY`

just make sure to use the full path to the file or copy it to the directory you run the command from

**Comment by Pajamaland** [comment]
> Going back to stock firmware on devices which are past EOL is not supported by the script and not recommended at all.
> 
> What are you trying to accomplish exactly?

Hey sorry to necro this but you wouldn't have a copy of the stock firmware for the Acer Chromebook 314 (DROID) I could use to get back to stock?

**Comment by MrChromebox** [comment]
> Hey sorry to necro this but you wouldn't have a copy of the stock firmware for the Acer Chromebook 314 (DROID) I could use to get back to stock?

I don't have stock firmware for any devices. The script provides an option to extract the generic stock firmware for a given board from the recovery USB. Alternatively, you can use coreboot's `crosfirmware.sh` script in `util/chromeos/` to accomplish the same thing if you need an image to flash externally.

**Comment by Vany913** [comment]
Sorry for the absence, I think I downloaded the file and then rebooted. When I got a white screen that said "ChromeOS verification is disabled" I pressed Ctrl+L and it sounded 2 beeps, what does that mean?

**Comment by MrChromebox** [comment]
> I pressed Ctrl+L and it sounded 2 beeps, what does that mean?

it means that dev_boot_legacy is not enabled, or that the RW_LEGACY payload is not bootable

**Comment by Vany913** [comment]
what to do to fix it?

**Comment by Vany913** [comment]
![IMG_20241107_194005](https://github.com/user-attachments/assets/0a04dbf8-f0bc-4d87-8320-be58ab35a058)
here is the log while flashing

**Comment by MrChromebox** [comment]
looks fine. now run `sudo crossystem dev_boot_legacy=1`

if still beeps, then need to flash RW_LEGACY differently I guess

**Comment by Vany913** [comment]
I was offered: PLEASE USE 'dev_boot_altfw' INSTEAD OF 'dev_boot_legacy' I did and it seems to have worked, ctrl+l now brings up a window I didn't see before and if you don't do anything it hangs with a black screen. And if you try again and then when you press esc you will be able to select the boot device. Should it be so?

**Comment by MrChromebox** [comment]
yes?

**Comment by MrChromebox** [comment]
as long as SeaBIOS is loading via RW_LEGACY, then I would use the firmware utility script under ChromeOS to set the GBB flags to legacy boot + 1s default, then boot and install your OS

**Comment by MrChromebox** [comment]
> I installed Ubuntu 24.04 to test and everything seems to work :). Can you write point by point what to do to make my OS default. P.S. on full firmware (uefi) i couldn't install linux if the kernel is newer than 4.15 and after a while the system froze and wouldn't boot anymore.

run my script from linux, and select the option to set the boot flags. set to legacy + 1s default.

**Comment by Vany913** [comment]
I have no way to set download marks.
![Uploading IMG_20241108_003038.jpg…]()

**Comment by Vany913** [comment]
I have no way to set download marks.
![IMG_20241108_003038](https://github.com/user-attachments/assets/12cd307d-cd42-4149-8164-b1e91b1e50b7)

**Comment by MrChromebox** [comment]
the script is not detecting the firmware type correctly, sigh. Google doing stupid shit on these older devices when booted in RW_LEGACY. what's the output of `sudo dmidecode -t 0`

**Comment by Vany913** [comment]
it doesn't seem to work :(

**Comment by MrChromebox** [comment]
I don't know what that means

**Comment by Vany913** [comment]
here I enter the command and then the result
![IMG_2024-11-08-21-39-21-753](https://github.com/user-attachments/assets/1ad8e7ce-7074-4e7e-a758-91f31cc10d46)
![IMG_2024-11-08-21-39-49-326](https://github.com/user-attachments/assets/360f57f8-228b-488c-8651-0579c8a41150)

**Comment by MrChromebox** [comment]
the problem is Google deleted the version field when booting RW_LEGACY, so I can't tell what firmware you are running.

exit the script and run these commands:
`cd /tmp`
`sudo ./gbb_utility --set --flags=0xa9 bios.bin`
`sudo ./flashrom -p internal -w bios.bin --fmap -i GBB -N`

if that works, you can reboot and it should auto boot to Linux

**Comment by Vany913** [comment]
after loading it stops there
![IMG_2024-11-08-22-19-51-412](https://github.com/user-attachments/assets/6d02cd74-d203-43c0-8859-ae0f8356a1c8)

**Comment by MrChromebox** [comment]
sorry, the flags should have been 0x4a9, so manually boot with CTRL+L *before* it boots to recovery, then re-run the script / re-run the commands above with the correct flags value

**Comment by Vany913** [comment]
The recovery mode screen appeared again with part of the command line, but after that Linux still booted. If this is how it should be, then that’s it, all the problems regarding rw_legacy seem to have been resolved. I am grateful to you :)

**Comment by MrChromebox** [comment]
that's not the recovery screen ("ChromeOS is missing or damaged"), that's the Developer Mode boot screen ("OS verification is off").

**Comment by Vany913** [comment]
I meant developer mode, sorry.

**Comment by MrChromebox** [comment]
right, that's the expected boot flow with the stock firmware. Only other thing you can do is strip out the bitmaps so that it's a black screen vs white

**Comment by Vany913** [comment]
ok, thanks again. I think we can close the question ;)
