### ISSUE TITLE
Script not starting on Falcon HP 14 CrOS 76

### ISSUE THREAD

**Issue by Fortato** [MrChromebox/scripts#433]
The script doesn't do anything, there are 0 errors and 0 messages appearing. I have previously dual booted Ubuntu but factory restarted since. I'm now trying to fully replace CrOS with arch but am having some trouble with this script. I tried running the script in guest mode and with a logged in user but neither work. Any help is appreciated.
![Screenshot 2024-11-02 at 11 52 48 AM](https://github.com/user-attachments/assets/53b10d67-44c6-4260-98e7-88411c81d465)

**Comment by MrChromebox** [comment]
sounds like curl is hanging for some reason. try using `-LOv` for verbose output, or `-LOk` to ignore SSL certificate issues (which are likely on a ChromeOS version that old).

I would have told you just to flash from Ubuntu FWIW =D

**Comment by Fortato** [comment]
i tried both and im having the same hanging issue, not sure where to move from here

**Comment by MrChromebox** [comment]
are your time/date correct? have you tried running from a VT2 terminal?

**Comment by Fortato** [comment]
time/date seem good. vt2 terminal also wasnt working

**Comment by MrChromebox** [comment]
FALCO should have functional RW_LEGACY OOTB, can you boot a live Linux USB and run the script from there?

**Comment by Fortato** [comment]
i used esc + refresh + power to get to the recovery screen, but when attempting to boot i get "the device you inserted does not contain chrome os", i tried that ctrl + l then after boot esc but nothing happens and after it stops beeping i return to a login screen.

**Comment by MrChromebox** [comment]
> i used esc + refresh + power to get to the recovery screen, but when attempting to boot i get "the device you inserted does not contain chrome os",

well yes, booting to recovery mode only allows you to boot recovery media -- that's how it works.

power on the device normally, and hit CTRL+L on the developer mode boot screen ("OS verification is off").
if it beeps, then boot ChromeOS and enable legacy boot mode by running the following in a shell: `sudo crossystem dev_boot_legacy=1` then reboot and try CTRL+L again

**Comment by Fortato** [comment]
oh that worked thanks, ill try running your script now

**Comment by Fortato** [comment]
So i finally got it working, ended up just reflashing chromeos after i accidentally broke it (oops!) but after the reinstall it worked perfectly fine. Thank for the help mr chromebox!
