### ISSUE TITLE
Can't return to stock firmware on acer chromebook CB315 BLORB

### ISSUE THREAD

**Issue by ynoalberto** [MrChromebox/scripts#435]
Hello

I have this error when I want to restore stock firmware in my acer chromebook CB315 BLORB using a ChromeOS Recovery USB in fedora 41:

cp: -r not specified; omitting directory '/tmp/tmp.QT9rIcvgVJ/'
Error: failed to extract firmware image for blorb using this recovery USB

**Comment by MrChromebox** [comment]
hmm, I just tested the extraction function on a blorb recovery image and it worked correctly. Are you sure the recovery USB is correct for blorb?

**Comment by ynoalberto** [comment]
Yes. I maje the recovery image U.S. Inf de chrome os utility. Have you any stock-firmware.rom file for my chromebook? Or Need I try with another USB?

**Comment by MrChromebox** [comment]
you can use the crosfirmware.sh script from https://github.com/coreboot/coreboot/tree/main/util/chromeos to do the same thing the firmware-util script does - downloads a recovery image and extracts the firmware for it. I tested it for blorb and no issues.

**Comment by ynoalberto** [comment]
I have this issue when extract the voreboot images. If you have this file for my mothderboard, send me here: 

![Captura desde 2024-11-08 13-58-05](https://github.com/user-attachments/assets/5543855d-acb2-4088-b979-98e32c2b3e9a)

**Comment by ynoalberto** [comment]
I don't know what's happends. You says don't have any issues, but I have some issues anda I'm sure that my board is BLORB

**Comment by MrChromebox** [comment]
I fixed the problem in the firmware-util.sh script the other day and in croshfirmware.sh just now.

this is the correct image for BLORB, though it does not have a valid HWID or correct GBB flags.
[coreboot-Google_Bobba.11297.357.0.zip](https://github.com/user-attachments/files/17683160/coreboot-Google_Bobba.11297.357.0.zip)

**Comment by ynoalberto** [comment]
Sorry. In the croshfirmware.sh I don't look any change on the github. But I will to try the file that you send me

**Comment by MrChromebox** [comment]
I just pushed a fix to the firmware-util. script. copy/paste error from the coreboot change

**Comment by ynoalberto** [comment]
All works fine. Thanks so much. Sorry for wasting your time.

**Comment by MrChromebox** [comment]
no worries, there was an issue with the script so good it got fixed
