### ISSUE TITLE
Cannot select 'restore stock firmware

### ISSUE THREAD

**Issue by D3dbyte** [MrChromebox/scripts#436]
I am trying to restore the stock os on a lenovo ideapad 3 15IGL05 and I am able to get to the part when I can choose option 2 to 'restore stock firmware' but when I type 2 and hit enter the 2 disappears and nothing happens.

I have tried this script in the terminal:

cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh

As well as this:

cd ~; curl -LO https://mrchromebox.tech/firmware-util.sh; sudo bash firmware-util.sh

Not sure why I am having an issue.

Any help would be appreciated.

**Comment by D3dbyte** [comment]
This isn't a chrome book. That's why it wouldn't work.

**Comment by D3dbyte** [comment]
Customer thought this was a chromebook but I checked manufacturer site and this pc was not sold with chrome OS.

Leaving open to confirm assumption

**Comment by MrChromebox** [comment]
not sure how I'm supposed to determine that given the info provided.

**Comment by D3dbyte** [comment]
Sorry I used https://psref.lenovo.com/ and put in the make and model. Found that this pc was only ever sold with windows operating systems.
