### ISSUE TITLE
Script not working on arch linux

### ISSUE THREAD

**Issue by PoPCaT6800** [MrChromebox/scripts#438]
Today i was attempting to run the Mr chromebox script to update coreboot on arch Linux. it failed with the following error.
I am unable to boot with a live usb, it does not show up in the bios or in the uefi shell when i run map -r.

`<pre>MrChromebox Firmware Utility Script starting up

Downloading supporting files...

Downloading required tools...

Getting device/system info...

<font color="#AA0000">Flashrom is unable to read current firmware; cannot continue:</font>

/tmp/flashrom: error while loading shared libraries: libftdi1.so.2: cannot open shared object file: No such file or directory

<font color="#AA0000">You may need to add &apos;iomem=relaxed&apos; to your kernel parameters,</font>
<font color="#AA0000">or trying running from a Live USB with a more permissive kernel (eg, Ubuntu 23.04+).</font>

<font color="#AA0000">If you have UEFI SecureBoot enabled, you need to disable it to run the script/update your firmware.</font>

MrChromebox Firmware Utility setup was unsuccessful
 * diagnosics report has been saved to /tmp/mrchromebox_diag.txt
 * go to https://forum.chrultrabook.com/ for help
</pre>`

**Comment by PoPCaT6800** [comment]
here is the file:
[flashrom.log](https://github.com/user-attachments/files/17778870/flashrom.log)
sorry for the inconvenience

**Comment by MrChromebox** [comment]
I just pushed an update to the script with a new flashrom build, see if that helps any

**Comment by PoPCaT6800** [comment]
i recieved this console error when running the script again.
`mrChromebox Firmware Utility Script starting up

Downloading supporting files...

Downloading required tools...

Getting device/system info...

Flashrom is unable to read current firmware; cannot continue:

flashrom MrChromebox-v1.5.0-devel (git:v1.4.0-89-gd2aaabbf7c) on Linux 6.10.9-arch1-2 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

/tmp/flashrom: unrecognized option '--use-first-chip'
Please run "flashrom --help" for usage info.

You may need to add 'iomem=relaxed' to your kernel parameters,
or trying running from a Live USB with a more permissive kernel (eg, Ubuntu 23.04+).

If you have UEFI SecureBoot enabled, you need to disable it to run the script/update your firmware.

MrChromebox Firmware Utility setup was unsuccessful
 * diagnosics report has been saved to /tmp/mrchromebox_diag.txt
 * go to https://forum.chrultrabook.com/ for help`

**Comment by MrChromebox** [comment]
remove the existing downloaded flashrom binary (/tmp/flashrom) and then the script will download the updated one

**Comment by PoPCaT6800** [comment]
i really appreciate all the help unfortunately my chromebook crashed and was bricked, i do appreciate the help though.
