### ISSUE TITLE
flashrom: unrecognized option '--use-first-chip'

### ISSUE THREAD

**Issue by p120ph37** [MrChromebox/scripts#439]
I have several Asus C202S chromebooks (terra) where the firmware-utility script works fine, but on one of them I'm getting an error.  Developer mode is active, the write-protect screw is removed, and I'm running from the `chronos` account on VT2.

When I try to launch the script, it tells me "Flashrom is unable to read current firmware; cannot continue:"

I tried both with the stock EOL ChromeOS, and after updating to the latest ChromeOS Flex version (131).

The contents of `/tmp/flashrom.log` say:
```
/usr/sbin/flashrom: unrecognized option '--use-first-chip'
Please run "flashrom --help" for usage info
```

After editing `firmware-utility.sh` to not download a fresh copy of the support scripts, and editing `functions.sh` to remove the `--use-first-chip` option, it worked.

**Comment by MrChromebox** [comment]
fixed -- that param should only be used when the script downloads flashrom under Linux
