### ISSUE TITLE
CX12 won't load Firmware script Could not resolve DNS Server

### ISSUE THREAD

**Issue by The-Captain56** [MrChromebox/scripts#443]
When running the script I get (6) could not resolve : mrchromebox.tech (could not contact DNS servers) Is this due to the EOL? If I'm past EOL what will work?

**Comment by MrChromebox** [comment]
you can simply open mrchromebox.tech in your browser, it has nothing to do with EOL. your DNS server is simply not accessible.

**Comment by MrChromebox** [comment]
closing as not a script (or server) issue
