### ISSUE TITLE
"unknown command cd" when trying to run firmware utility script...

### ISSUE THREAD

**Issue by juddagain** [MrChromebox/scripts#449]
I have a QUAWKS hwid/board in my Asus C300 chromebook. When I am trying to run the firmware utility script from CROSH, I get "unknown command cd".

cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh

I am trying to convert the old Chrome OS to Flex and read that I needed to update the firmware. I have already removed the WP screw.

I am a novice. Thanks in advance for any help that you can give.

**Comment by MrChromebox** [comment]
If running the script from a crosh shell, you need to type `shell` and press enter before entering the script command line
