### ISSUE TITLE
entering "shell" creates error in Crosh...

### ISSUE THREAD

**Issue by juddagain** [MrChromebox/scripts#450]
When I enter "shell" into CROSH, I get "ERROR: unknown command: shell". I was told to enter shell first before the firmware utility script as I was getting an error with it. See below.

I have a QUAWKS hwid/board in my Asus C300 chromebook. When I am trying to run the firmware utility script from CROSH, I get "unknown command cd".

cd; curl -LO mrchromebox.tech/firmware-util.sh && sudo bash firmware-util.sh

I am trying to convert the old Chrome OS to Flex and read that I needed to update the firmware. I have already removed the WP screw.

I am a novice. Thanks in advance for any help that you can give.

**Comment by MrChromebox** [comment]
please read the full instructions on mrchromebox.tech - you need to put your device into developer mode before `shell` is available
