### ISSUE TITLE
Please help I have no clue what's happening 

### ISSUE THREAD

**Issue by matthew767836873563** [MrChromebox/scripts#452]
One of two things happen when I'm messing around in the menu I either get taken to the shell script where I just type exit or I get this black screen pop up saying "booting from 'eMMC Device's failed: verify it contains a 64 bit UEFI OS." Please help me, this is the first time I've ever done anything like this, I just want my laptop to work

**Comment by MrChromebox** [comment]
please post on the chrultrabook forums for help, this isn't an issue with my firmware utility script

**Comment by matthew767836873563** [comment]
Okay, thank you for letting me know
