### ISSUE TITLE
Firmware Checksum download fail

### ISSUE THREAD

**Issue by IsaacPaczkowski** [MrChromebox/scripts#57]
While trying to a full ROM install, it ends by saying the firmware could not be downloaded and that it cannot flash. Please Help!

**Comment by MrChromebox** [comment]
@IsaacPaczkowski might be helpful if you told me what device you were using, and what the exact error is (a picture works well here).  Also, try again in case it was a simple download error (and be glad the script prevented you from flashing a bad file).

**Comment by IsaacPaczkowski** [comment]
Lol, yeah, you're right! Dont want bad firmware. My bad on not including the Info: I am Currently using a Samsung xe500c13 (Celes is the codename) and has an Celeron processor (Braswell).
![dsc_0001](https://user-images.githubusercontent.com/35548287/42463824-45cdf154-8375-11e8-933b-c0c5750bbb12.JPG)
![dsc_0002](https://user-images.githubusercontent.com/35548287/42463826-45d9f92c-8375-11e8-882a-b12904c1ce99.JPG)
![dsc_0003](https://user-images.githubusercontent.com/35548287/42463827-45e7cef8-8375-11e8-8522-d4a62a57f34b.JPG)


 I have removed the WP screw and enabled dev mode. (Error and scripts pictured:)

**Comment by MrChromebox** [comment]
@IsaacPaczkowski something on your end is breaking the download - the file exists on the server, the checksum is correct, and there's no download error in the server logs

**Comment by IsaacPaczkowski** [comment]
I'm sure this is probably it, but, could it be my trying to do this on a business network that uses securities such as Smoothwall, and etc? (Can't believe I didn't think about that...)
