### ISSUE TITLE
Firmware Script not working on pixel 2013

### ISSUE THREAD

**Issue by pitweval** [MrChromebox/scripts#58]
I'm probably doing something wrong but when I run the script it claims to have installed the firmware but when I re-run the script or boot into legacy mpeode it still says it's running the offical google firmware.

The Script says:
Device: Google Chromebook Pixel 2013 (LINK)
CPU Type: Intel IvyBridge
Fw Type: Stock ChromeOS
Fw WP: Enabled

Is there something I am doing wrong?

**Comment by MrChromebox** [comment]
nothing wrong, just two issues at play here:
- the script doesn't distinguish between 'Stock ChromeOS' and 'Stock w/RW_LEGACY' when running under ChromeOS, it is an area I could improve
- the 2013 Pixel doesn't have a RW_LEGACY firmware made by me, I just supply one made by google
