### ISSUE TITLE
Removing Chrome OS Bitmaps not working on Pixelbook (2013)

### ISSUE THREAD

**Issue by pitweval** [MrChromebox/scripts#59]
I removed the write protection screw, and was able to change the boot order with out issue, but when I try to remove (replace?) the google splash screens it doesn't seem to do anything.  Rebooting after selecting that option still shows the ugly white background.

**Comment by MrChromebox** [comment]
might not work on the 2013 Chromebook Pixel, it's a bit of an oddball firmware-wise.  If I have some time, will see if I can reproduce here / find a fix

**Comment by pitweval** [comment]
Not a blocking issue for sure, just wanted to see if it was a known issue.

**Comment by MrChromebox** [comment]
found/fixed the issue, script update pushed :)
