### ISSUE TITLE
(MICRO) sd card not showing up in boot menu or at all

### ISSUE THREAD

**Issue by pcs3rd** [MrChromebox/scripts#63]
Installed Gallium os on a microsdcard. Booting on a Braswell Chromebook with RW_LEGACY updated. No errors, just microsdcard not showing up.

**Comment by MrChromebox** [comment]
which device? Tried more than one SD card? SeaBIOS has detection issues with some higher capacity/high speed cards

SD cards are showing up correctly here on CELES and CYAN with latest BSW RW_LEGACY

**Comment by MrChromebox** [comment]
closing this as it's 1) a firmware issue, not a script one, and 2) likely resolved in the 2018.09.12 RW_LEGACY update
