### ISSUE TITLE
Unable to download Full ROM Firmware

### ISSUE THREAD

**Issue by julink17** [MrChromebox/scripts#67]
I have tried to setup an Acer Chromebase24 with UFEI Full ROM, but it just keeps failing when it tries to download the ROM.
![5fd6e337-9715-4386-bc5e-960a365ab54f](https://user-images.githubusercontent.com/25254175/45838153-aca02600-bcd6-11e8-821e-b4c8ce6d2026.jpeg)

**Comment by MrChromebox** [comment]
BUDDY actually isn't supported at the moment for UEFI full ROM firmware, so the error is in showing it as available, not in the download failing. I've built a test ROM for it but still waiting on feedback from a tester before I push it live

**Comment by julink17** [comment]
I see, my apologies, I only saw that the Broadwell CPU was capable.  Would it be possible for me test it on my machines as well?  I’m not concern about bricking it.

**Comment by MrChromebox** [comment]
No, not your error, issue was/is with the script advertising a function that is not available for your device. Shoot me an email at MrChromebox at Gmail and I'll provide instructions
