### ISSUE TITLE
Syntax Error near unexpected token `newline'

### ISSUE THREAD

**Issue by Simon5886** [MrChromebox/scripts#68]
Using a acer chromebook r11  (model N15Q8).

```
firmware-util.sh: line 3: syntax error near unexpected token `newline'
firmware-util.sh: line 3: `<!DOCTYPE HTML PUBLIC "-//W3C??DTD HTML 4.01//EN" "http:// www.w3.org/TR/html4/strict.dtd">'
```

It prevents me running the script

Any help would be appreciated.

Thanks,

**Comment by MrChromebox** [comment]
looks like the file simply failed to download and you got a html doc instead, I'd just retry as there's nothing wrong on the server side best I can tell
