### ISSUE TITLE
firmware-util.sh not properly detecting write protection state

### ISSUE THREAD

**Issue by chilaxan** [MrChromebox/scripts#75]
![image](https://user-images.githubusercontent.com/35645806/49537252-7f572300-f896-11e8-8ef9-1b9568539038.png)
![image](https://user-images.githubusercontent.com/35645806/49537266-8b42e500-f896-11e8-890a-4e6f2c9e48f8.png)

**Comment by MrChromebox** [comment]
software and hardware write protect are two different things, the script reports the latter when run from under ChromeOS

**Comment by chilaxan** [comment]
I tested editing the boot options using gbb_utility to shorten the delay and that worked.

**Comment by MrChromebox** [comment]
did you previously disable the software WP while the hardware WP was disabled?

**Comment by chilaxan** [comment]
yes

**Comment by chilaxan** [comment]
using `flashrom -p host --wp-disable` and `flashrom -p ec --wp-disable`

**Comment by MrChromebox** [comment]
well that's why, the script is defaulting to the more conservative position, since the hardware WP is enabled, and not expecting users to have manually disabled the software WP.  I suppose I can adjust since newer devices with battery sense WP are more likely to have hardware WP re-enabled

**Comment by chilaxan** [comment]
makes sense

**Comment by MrChromebox** [comment]
what I'll need to do is report both the HW and software WP state, and add a menu option to toggle the SW wp state

**Comment by chilaxan** [comment]
im glad to test any changes

**Comment by MrChromebox** [comment]
I have a few APL/KBL devices here I can test on, so should be good, but I'll let you know

**Comment by chilaxan** [comment]
ok
