### ISSUE TITLE
Problem flashing full ROM on Google Chromebook Pixel 2013 (link)

### ISSUE THREAD

**Issue by kraml** [MrChromebox/scripts#77]
I have no problem flashing RW_LEGACY firmware on this device. But when I tried to flash the full ROM, I got below error from flashrom:

Invalid entry specified: SI_BIOS

Then the flash failed. Please see attached screenshot for the full output:

FW WP is off as in this one:

![link 1](https://user-images.githubusercontent.com/358679/50637728-1696bf80-0f96-11e9-9822-9e555dea7012.jpg)

Flash failed.

![link 2](https://user-images.githubusercontent.com/358679/50637754-30380700-0f96-11e9-92b4-82197fa5b109.jpg)

Anything I can do to help diagnostic this problem?

**Comment by kraml** [comment]
Sorry the pics seems too big, I should have shrunk them, sorry for that.

**Comment by kraml** [comment]
The problem only occurred when I run the script from within ChromeOS 69, the last and the latest version for this device.

There is no any problem when I ran it from Linux, the UEFI full ROM was installed successfully.

**Comment by MrChromebox** [comment]
grr, reverted this change while I figure out why it's not working consistently/correctly.
