### ISSUE TITLE
secure boot and tpm for windows.

### ISSUE THREAD

**Issue by shuxin** [MrChromebox/scripts#88]
is there a way to enable secure boot for windows? 
so does the tpm chip.
the tpm could be seen, but cannot work.

**Comment by MrChromebox** [comment]
not currently, need to get TPM working under Tianocore first, then can hook up SB.  It's on my radar but not a super-high priority currently

**Comment by MrChromebox** [comment]
also, closing this since it's not a script issue, and a similar issue already exists under the correct tracker: 
https://github.com/MrChromebox/firmware/issues/132
