### ISSUE TITLE
Stoney Ridge (Grunt) support

### ISSUE THREAD

**Issue by DennisLfromGA** [MrChromebox/scripts#90]
Just curious if anything is in the works for the new AMD devices.

Had a question on Discord r/ChromeOS from someone wanting to install a full ROM but it doesn't look like grunt is supported in the firmware utility script yet.

-**DennisLfromGA**

**Comment by MrChromebox** [comment]
I'm working on RW_LEGACY support for GRUNT, but won't be ready for the upcoming 4.10 coreboot release. AMD devices have some unique quirks that I'm still trying to work around.

**Comment by MrChromebox** [comment]
Stoneyridge support was added long ago
