### ISSUE TITLE
Firmware checksum fail; download corrupted

### ISSUE THREAD

**Issue by wings2048** [MrChromebox/scripts#92]
I have a Acer chromebook 15, I have tried a different network in case my network was causing the issue, however the result is the same.
The rom backed up just fine. 

![IMG_20190909_123349](https://user-images.githubusercontent.com/55104459/64553580-3f2e4080-d2ff-11e9-9dca-9e378776343c.jpg)
![IMG_20190909_123407](https://user-images.githubusercontent.com/55104459/64553581-3f2e4080-d2ff-11e9-8d26-0ec0b7f55326.jpg)

**Comment by MrChromebox** [comment]
run my script, not coolstar's

<sigh>
